// Gestão de Criativos — Exports
export { UGCClientTab } from './UGCClientTab';
export { UGCAITab } from './UGCAITab';
export { ProductVideoTab } from './ProductVideoTab';
export { ProductImageTab } from './ProductImageTab';
export { AvatarMascotTab } from './AvatarMascotTab';
export { CreativeJobsList } from './CreativeJobsList';
export { CreativeGallery } from './CreativeGallery';
export { VoiceSelector } from './VoiceSelector';
export { VoicePresetManager } from './VoicePresetManager';
export { VideoJobsList } from './VideoJobsList';
