// =============================================
// BLOCK REGISTRY - Central registry of all blocks
// =============================================

import type { BlockCategory, BlockDefinition, BlockNode } from './types';

// Block definitions
const blockDefinitions: BlockDefinition[] = [
  // ========== LAYOUT BLOCKS ==========
  {
    type: 'Page',
    label: 'Página',
    category: 'layout',
    icon: 'FileText',
    defaultProps: {
      backgroundColor: 'transparent',
      padding: 'none',
    },
    propsSchema: {
      backgroundColor: {
        type: 'color',
        label: 'Cor de Fundo',
        defaultValue: 'transparent',
      },
      padding: {
        type: 'select',
        label: 'Espaçamento',
        defaultValue: 'none',
        options: [
          { label: 'Nenhum', value: 'none' },
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
        ],
      },
    },
    canHaveChildren: true,
    isRemovable: false,
  },
  {
    type: 'Section',
    label: 'Seção',
    category: 'layout',
    icon: 'LayoutDashboard',
    defaultProps: {
      backgroundColor: 'transparent',
      paddingX: 16,
      paddingY: 32,
      marginTop: 0,
      marginBottom: 0,
      gap: 16,
      alignItems: 'stretch',
      fullWidth: false,
    },
    propsSchema: {
      backgroundColor: {
        type: 'color',
        label: 'Cor de Fundo',
        defaultValue: 'transparent',
      },
      paddingX: {
        type: 'number',
        label: 'Padding Horizontal (px)',
        defaultValue: 16,
        min: 0,
        max: 100,
      },
      paddingY: {
        type: 'number',
        label: 'Padding Vertical (px)',
        defaultValue: 32,
        min: 0,
        max: 200,
      },
      marginTop: {
        type: 'number',
        label: 'Margem Superior (px)',
        defaultValue: 0,
        min: 0,
        max: 200,
      },
      marginBottom: {
        type: 'number',
        label: 'Margem Inferior (px)',
        defaultValue: 0,
        min: 0,
        max: 200,
      },
      gap: {
        type: 'number',
        label: 'Espaço entre Itens (px)',
        defaultValue: 16,
        min: 0,
        max: 100,
      },
      alignItems: {
        type: 'select',
        label: 'Alinhamento Vertical',
        defaultValue: 'stretch',
        options: [
          { label: 'Esticar', value: 'stretch' },
          { label: 'Início', value: 'flex-start' },
          { label: 'Centro', value: 'center' },
          { label: 'Fim', value: 'flex-end' },
        ],
      },
      fullWidth: {
        type: 'boolean',
        label: 'Largura Total',
        defaultValue: false,
      },
    },
    canHaveChildren: true,
  },
  {
    type: 'Container',
    label: 'Container',
    category: 'layout',
    icon: 'Square',
    defaultProps: {
      maxWidth: 'lg',
      padding: 16,
      marginTop: 0,
      marginBottom: 0,
      gap: 16,
    },
    propsSchema: {
      maxWidth: {
        type: 'select',
        label: 'Largura Máxima',
        defaultValue: 'lg',
        options: [
          { label: 'Pequeno (640px)', value: 'sm' },
          { label: 'Médio (768px)', value: 'md' },
          { label: 'Grande (1024px)', value: 'lg' },
          { label: 'Extra Grande (1280px)', value: 'xl' },
          { label: 'Total', value: 'full' },
        ],
      },
      padding: {
        type: 'number',
        label: 'Padding (px)',
        defaultValue: 16,
        min: 0,
        max: 100,
      },
      marginTop: {
        type: 'number',
        label: 'Margem Superior (px)',
        defaultValue: 0,
        min: 0,
        max: 200,
      },
      marginBottom: {
        type: 'number',
        label: 'Margem Inferior (px)',
        defaultValue: 0,
        min: 0,
        max: 200,
      },
      gap: {
        type: 'number',
        label: 'Espaço entre Itens (px)',
        defaultValue: 16,
        min: 0,
        max: 100,
      },
    },
    canHaveChildren: true,
  },
  {
    type: 'Columns',
    label: 'Colunas',
    category: 'layout',
    icon: 'Columns',
    defaultProps: {
      columns: 2,
      gap: 16,
      stackOnMobile: true,
      alignItems: 'stretch',
    },
    propsSchema: {
      columns: {
        type: 'select',
        label: 'Número de Colunas',
        defaultValue: '2',
        options: [
          { label: '2 Colunas', value: '2' },
          { label: '3 Colunas', value: '3' },
          { label: '4 Colunas', value: '4' },
        ],
      },
      gap: {
        type: 'number',
        label: 'Espaçamento (px)',
        defaultValue: 16,
        min: 0,
        max: 100,
      },
      stackOnMobile: {
        type: 'boolean',
        label: 'Empilhar no Mobile',
        defaultValue: true,
      },
      alignItems: {
        type: 'select',
        label: 'Alinhamento Vertical',
        defaultValue: 'stretch',
        options: [
          { label: 'Esticar', value: 'stretch' },
          { label: 'Início', value: 'flex-start' },
          { label: 'Centro', value: 'center' },
          { label: 'Fim', value: 'flex-end' },
        ],
      },
    },
    canHaveChildren: true,
    slotConstraints: { maxChildren: 4 },
  },
  {
    type: 'Divider',
    label: 'Divisor',
    category: 'layout',
    icon: 'Minus',
    defaultProps: {
      style: 'solid',
      color: '#e5e7eb',
    },
    propsSchema: {
      style: {
        type: 'select',
        label: 'Estilo',
        defaultValue: 'solid',
        options: [
          { label: 'Sólido', value: 'solid' },
          { label: 'Tracejado', value: 'dashed' },
          { label: 'Pontilhado', value: 'dotted' },
        ],
      },
      color: {
        type: 'color',
        label: 'Cor',
        defaultValue: '#e5e7eb',
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'Spacer',
    label: 'Espaçador',
    category: 'layout',
    icon: 'MoveVertical',
    defaultProps: {
      height: 'md',
    },
    propsSchema: {
      height: {
        type: 'select',
        label: 'Altura',
        defaultValue: 'md',
        options: [
          { label: 'Extra Pequeno', value: 'xs' },
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
          { label: 'Extra Grande', value: 'xl' },
        ],
      },
    },
    canHaveChildren: false,
  },

  // ========== HEADER / FOOTER BLOCKS ==========
  {
    type: 'Header',
    label: 'Cabeçalho',
    category: 'header-footer',
    icon: 'PanelTop',
    defaultProps: {
      menuId: '',
      showSearch: true,
      showCart: true,
      sticky: true,
      // Estilo do cabeçalho (Yampi)
      headerStyle: 'logo_left_menu_inline',
      headerBgColor: '',
      headerTextColor: '',
      headerIconColor: '',
      // Cores do menu (para estilos "menu abaixo")
      menuBgColor: '',
      menuTextColor: '',
      // Sticky mobile
      stickyOnMobile: true,
      // Contato no cabeçalho
      showWhatsApp: false,
      whatsAppNumber: '',
      whatsAppLabel: '',
      showPhone: false,
      phoneNumber: '',
      phoneLabel: '',
      // REMOVIDO: Categorias no cabeçalho (menu vem do Menu Builder)
      // Área do Cliente
      customerAreaEnabled: false,
      customerAreaLabel: 'Minhas compras',
      // Promoções em Destaque
      featuredPromosEnabled: false,
      featuredPromosLabel: 'Promoções',
      featuredPromosTextColor: '#d97706',
      featuredPromosPageId: '',
      featuredPromosPageSlug: '', // Legacy support
      // Barra Superior (Aviso Geral)
      noticeEnabled: false,
      noticeText: '',
      noticeBgColor: '#1e40af',
      noticeTextColor: '#ffffff',
      noticeAnimation: 'fade',
      // Barra Superior - ação
      noticeActionEnabled: false,
      noticeActionLabel: '',
      noticeActionUrl: '',
      noticeActionTarget: '_self',
      noticeActionTextColor: '',
    },
    propsSchema: {
      // === ESTILO DO CABEÇALHO ===
      headerStyle: {
        type: 'select',
        label: 'Estilo do Cabeçalho',
        defaultValue: 'logo_left_menu_inline',
        options: [
          { label: 'Logo à esquerda, menu ao lado', value: 'logo_left_menu_inline' },
          { label: 'Logo à esquerda, menu abaixo', value: 'logo_left_menu_below' },
          { label: 'Logo centralizado, menu abaixo', value: 'logo_center_menu_below' },
        ],
      },
      // === CORES DO CABEÇALHO ===
      headerBgColor: {
        type: 'color',
        label: 'Cor de Fundo',
        placeholder: 'Padrão do tema',
      },
      headerTextColor: {
        type: 'color',
        label: 'Cor do Texto',
        placeholder: 'Padrão do tema',
      },
      headerIconColor: {
        type: 'color',
        label: 'Cor dos Ícones',
        placeholder: 'Padrão do tema',
      },
      // === CORES DO MENU (para estilos "menu abaixo") ===
      menuBgColor: {
        type: 'color',
        label: 'Cor de Fundo do Menu',
        placeholder: 'Mesmo do cabeçalho',
      },
      menuTextColor: {
        type: 'color',
        label: 'Cor do Texto do Menu',
        placeholder: 'Mesmo do cabeçalho',
      },
      // === CONFIGURAÇÕES GERAIS ===
      stickyOnMobile: {
        type: 'boolean',
        label: 'Fixar ao rolar (Mobile)',
        defaultValue: true,
      },
      sticky: {
        type: 'boolean',
        label: 'Fixo no Topo (Desktop)',
        defaultValue: true,
      },
      menuId: {
        type: 'menu',
        label: 'Menu',
        placeholder: 'Selecione um menu',
      },
      showSearch: {
        type: 'boolean',
        label: 'Mostrar Busca',
        defaultValue: true,
      },
      showCart: {
        type: 'boolean',
        label: 'Mostrar Carrinho',
        defaultValue: true,
      },
      // === CONTATO NO CABEÇALHO ===
      showWhatsApp: {
        type: 'boolean',
        label: 'Mostrar WhatsApp',
        defaultValue: false,
      },
      whatsAppNumber: {
        type: 'string',
        label: 'Número do WhatsApp',
        placeholder: 'Ex: 5511999999999',
      },
      whatsAppLabel: {
        type: 'string',
        label: 'Texto do WhatsApp (opcional)',
        placeholder: 'Ex: WhatsApp',
      },
      showPhone: {
        type: 'boolean',
        label: 'Mostrar Telefone',
        defaultValue: false,
      },
      phoneNumber: {
        type: 'string',
        label: 'Número do Telefone',
        placeholder: 'Ex: +55 (11) 99999-9999',
      },
      phoneLabel: {
        type: 'string',
        label: 'Texto do Telefone (opcional)',
        placeholder: 'Ex: Atendimento',
      },
      // REMOVIDO: Categorias no cabeçalho (menu vem do Menu Builder)
      // === ÁREA DO CLIENTE ===
      customerAreaEnabled: {
        type: 'boolean',
        label: 'Exibir "Minhas compras"',
        defaultValue: false,
      },
      customerAreaLabel: {
        type: 'string',
        label: 'Texto do link',
        defaultValue: 'Minhas compras',
        placeholder: 'Ex: Minhas compras',
      },
      // === PROMOÇÕES EM DESTAQUE ===
      featuredPromosEnabled: {
        type: 'boolean',
        label: 'Exibir link de Promoções',
        defaultValue: false,
      },
      featuredPromosLabel: {
        type: 'string',
        label: 'Texto do link',
        defaultValue: 'Promoções',
        placeholder: 'Ex: Promoções',
      },
      featuredPromosTextColor: {
        type: 'color',
        label: 'Cor do texto',
        defaultValue: '#d97706',
        placeholder: 'Ex: #d97706 (dourado)',
      },
      featuredPromosPageId: {
        type: 'string',
        label: 'Página de promoções',
        placeholder: 'Selecione uma página',
      },
      // Legacy prop - removed from schema as editor manages via ID now
      // === BARRA SUPERIOR (AVISO GERAL) ===
      noticeEnabled: {
        type: 'boolean',
        label: 'Exibir Barra Superior',
        defaultValue: false,
      },
      noticeText: {
        type: 'string',
        label: 'Texto',
        placeholder: 'Ex: Frete grátis em compras acima de R$199!',
      },
      noticeBgColor: {
        type: 'color',
        label: 'Cor de Fundo',
        defaultValue: '#1e40af',
      },
      noticeTextColor: {
        type: 'color',
        label: 'Cor do Texto',
        defaultValue: '#ffffff',
      },
      noticeAnimation: {
        type: 'select',
        label: 'Animação de Entrada',
        defaultValue: 'fade',
        options: [
          { label: 'Nenhuma', value: 'none' },
          { label: 'Fade', value: 'fade' },
          { label: 'Slide', value: 'slide' },
        ],
      },
      // Barra Superior - ação
      noticeActionEnabled: {
        type: 'boolean',
        label: 'Exibir Ação',
        defaultValue: false,
      },
      noticeActionLabel: {
        type: 'string',
        label: 'Texto da Ação',
        placeholder: 'Ex: Saiba mais',
      },
      noticeActionUrl: {
        type: 'string',
        label: 'URL da Ação',
        placeholder: 'Ex: /promocao',
      },
      noticeActionTarget: {
        type: 'select',
        label: 'Abrir em',
        defaultValue: '_self',
        options: [
          { label: 'Mesma aba', value: '_self' },
          { label: 'Nova aba', value: '_blank' },
        ],
      },
      noticeActionTextColor: {
        type: 'color',
        label: 'Cor do Texto da Ação',
      },
    },
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'Footer',
    label: 'Rodapé da Loja',
    category: 'header-footer',
    icon: 'PanelBottom',
    defaultProps: {
      // Seções (toggles)
      showLogo: true,
      showSac: true,
      showSocial: true,
      showLegal: true,
      // Conteúdo (override opcional)
      sacTitle: 'Atendimento (SAC)',
      legalTextOverride: '',
      // Cores do rodapé
      footerBgColor: '',
      footerTextColor: '',
      // Seções de imagens
      paymentMethods: { title: 'Formas de Pagamento', items: [] },
      securitySeals: { title: 'Selos de Segurança', items: [] },
      shippingMethods: { title: 'Formas de Envio', items: [] },
      officialStores: { title: 'Lojas Oficiais', items: [] },
    },
    propsSchema: {
      // === SEÇÕES ===
      showLogo: {
        type: 'boolean',
        label: 'Mostrar Logo',
        defaultValue: true,
      },
      showSac: {
        type: 'boolean',
        label: 'Mostrar Atendimento (SAC)',
        defaultValue: true,
      },
      showSocial: {
        type: 'boolean',
        label: 'Mostrar Redes Sociais',
        defaultValue: true,
      },
      showLegal: {
        type: 'boolean',
        label: 'Mostrar Informações Legais',
        defaultValue: true,
      },
      // === CONTEÚDO ===
      sacTitle: {
        type: 'string',
        label: 'Título do SAC',
        defaultValue: 'Atendimento (SAC)',
        placeholder: 'Ex: Atendimento ao Cliente',
      },
      legalTextOverride: {
        type: 'string',
        label: 'Texto Legal Personalizado',
        placeholder: 'Deixe vazio para usar dados da loja (CNPJ, endereço, etc.)',
      },
      // === CORES DO RODAPÉ ===
      footerBgColor: {
        type: 'color',
        label: 'Cor de Fundo',
        placeholder: 'Padrão do tema',
      },
      footerTextColor: {
        type: 'color',
        label: 'Cor do Texto',
        placeholder: 'Padrão do tema',
      },
      // === SEÇÕES DE IMAGENS ===
      paymentMethods: {
        type: 'array',
        label: 'Formas de Pagamento',
      },
      securitySeals: {
        type: 'array',
        label: 'Selos de Segurança',
      },
      shippingMethods: {
        type: 'array',
        label: 'Formas de Envio',
      },
      officialStores: {
        type: 'array',
        label: 'Lojas Oficiais',
      },
    },
    canHaveChildren: false,
    isRemovable: false,
  },

  // ========== CONTENT BLOCKS ==========
  {
    type: 'Hero',
    label: 'Banner de Destaque',
    category: 'content',
    icon: 'Image',
    defaultProps: {
      title: 'Bem-vindo à Nossa Loja',
      subtitle: 'Descubra produtos incríveis',
      imageDesktop: '',
      imageMobile: '',
      backgroundColor: '#6366f1',
      textColor: '#ffffff',
      buttonText: 'Ver Produtos',
      buttonUrl: '/produtos',
      buttonColor: '#ffffff',
      buttonTextColor: '',
      buttonHoverBgColor: '',
      buttonHoverTextColor: '',
      alignment: 'center',
      overlayOpacity: 50,
      height: 'md',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Bem-vindo à Nossa Loja',
      },
      subtitle: {
        type: 'string',
        label: 'Subtítulo',
        defaultValue: 'Descubra produtos incríveis',
      },
      imageDesktop: {
        type: 'image',
        label: 'Imagem Desktop',
        helpText: 'Recomendado: 1920×700px (proporção ~16:6)',
      },
      imageMobile: {
        type: 'image',
        label: 'Imagem Mobile',
        placeholder: 'Opcional - usa Desktop se vazio',
        helpText: 'Recomendado: 1080×1350px (proporção 4:5)',
      },
      backgroundColor: {
        type: 'color',
        label: 'Cor de Fundo (se sem imagem)',
        defaultValue: '#6366f1',
      },
      textColor: {
        type: 'color',
        label: 'Cor do Texto',
        defaultValue: '#ffffff',
      },
      buttonText: {
        type: 'string',
        label: 'Texto do Botão',
        defaultValue: 'Ver Produtos',
      },
      buttonUrl: {
        type: 'string',
        label: 'Link do Botão',
        defaultValue: '/produtos',
      },
      buttonColor: {
        type: 'color',
        label: 'Cor de Fundo do Botão',
        defaultValue: '#ffffff',
      },
      buttonTextColor: {
        type: 'color',
        label: 'Cor do Texto do Botão',
      },
      buttonHoverBgColor: {
        type: 'color',
        label: 'Cor de Fundo (Hover)',
      },
      buttonHoverTextColor: {
        type: 'color',
        label: 'Cor do Texto (Hover)',
      },
      alignment: {
        type: 'select',
        label: 'Alinhamento',
        defaultValue: 'center',
        options: [
          { label: 'Esquerda', value: 'left' },
          { label: 'Centro', value: 'center' },
          { label: 'Direita', value: 'right' },
        ],
      },
      height: {
        type: 'select',
        label: 'Altura',
        defaultValue: 'md',
        options: [
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
          { label: 'Tela Cheia', value: 'full' },
        ],
      },
      overlayOpacity: {
        type: 'number',
        label: 'Opacidade do Overlay (%)',
        defaultValue: 50,
        min: 0,
        max: 100,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'RichText',
    label: 'Texto',
    category: 'content',
    icon: 'FileText',
    defaultProps: {
      content: '<p>Digite seu conteúdo aqui...</p>',
      fontFamily: 'inherit',
      fontSize: 'base',
      fontWeight: 'normal',
    },
    propsSchema: {
      content: {
        type: 'richtext',
        label: 'Conteúdo',
        defaultValue: '<p>Digite seu conteúdo aqui...</p>',
      },
      fontFamily: {
        type: 'select',
        label: 'Fonte',
        defaultValue: 'inherit',
        options: [
          { label: 'Padrão do tema', value: 'inherit' },
          { label: 'Sans-serif', value: 'system-ui, sans-serif' },
          { label: 'Serif', value: 'Georgia, serif' },
          { label: 'Mono', value: 'monospace' },
          { label: 'Inter', value: 'Inter, sans-serif' },
          { label: 'Roboto', value: 'Roboto, sans-serif' },
          { label: 'Open Sans', value: 'Open Sans, sans-serif' },
          { label: 'Playfair Display', value: 'Playfair Display, serif' },
        ],
      },
      fontSize: {
        type: 'select',
        label: 'Tamanho',
        defaultValue: 'base',
        options: [
          { label: 'Extra Pequeno', value: 'xs' },
          { label: 'Pequeno', value: 'sm' },
          { label: 'Normal', value: 'base' },
          { label: 'Grande', value: 'lg' },
          { label: 'Extra Grande', value: 'xl' },
          { label: '2XL', value: '2xl' },
        ],
      },
      fontWeight: {
        type: 'select',
        label: 'Peso',
        defaultValue: 'normal',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Médio', value: '500' },
          { label: 'Semi-negrito', value: '600' },
          { label: 'Negrito', value: 'bold' },
        ],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'PageContent',
    label: 'Conteúdo da Página',
    category: 'content',
    icon: 'FileInput',
    defaultProps: {},
    propsSchema: {},
    canHaveChildren: false,
  },
  {
    type: 'Image',
    label: 'Imagem',
    category: 'media',
    icon: 'ImageIcon',
    defaultProps: {
      imageDesktop: '',
      imageMobile: '',
      alt: 'Imagem',
      width: 'full',
      height: 'auto',
      objectFit: 'cover',
      objectPosition: 'center',
      aspectRatio: 'auto',
      rounded: 'none',
      shadow: 'none',
      linkUrl: '',
    },
    propsSchema: {
      imageDesktop: {
        type: 'image',
        label: 'Imagem Desktop',
        helpText: 'Recomendado: 1200×800px (proporção 3:2)',
      },
      imageMobile: {
        type: 'image',
        label: 'Imagem Mobile',
        placeholder: 'Opcional - usa Desktop se vazio',
        helpText: 'Recomendado: 800×1000px (proporção 4:5)',
      },
      alt: {
        type: 'string',
        label: 'Texto Alternativo',
        defaultValue: 'Imagem',
      },
      linkUrl: {
        type: 'string',
        label: 'Link (opcional)',
        placeholder: 'URL de destino ao clicar',
      },
      width: {
        type: 'select',
        label: 'Largura',
        defaultValue: 'full',
        options: [
          { label: '25%', value: '25' },
          { label: '50%', value: '50' },
          { label: '75%', value: '75' },
          { label: '100%', value: 'full' },
        ],
      },
      height: {
        type: 'select',
        label: 'Altura',
        defaultValue: 'auto',
        options: [
          { label: 'Automático', value: 'auto' },
          { label: '200px', value: '200px' },
          { label: '300px', value: '300px' },
          { label: '400px', value: '400px' },
          { label: '500px', value: '500px' },
          { label: '50vh', value: '50vh' },
          { label: '75vh', value: '75vh' },
        ],
      },
      aspectRatio: {
        type: 'select',
        label: 'Proporção',
        defaultValue: 'auto',
        options: [
          { label: 'Automático', value: 'auto' },
          { label: '1:1 (Quadrado)', value: '1:1' },
          { label: '4:3', value: '4:3' },
          { label: '16:9', value: '16:9' },
          { label: '21:9 (Ultra wide)', value: '21:9' },
        ],
      },
      objectFit: {
        type: 'select',
        label: 'Enquadramento',
        defaultValue: 'cover',
        options: [
          { label: 'Cobrir', value: 'cover' },
          { label: 'Conter', value: 'contain' },
          { label: 'Preencher', value: 'fill' },
          { label: 'Nenhum', value: 'none' },
        ],
      },
      objectPosition: {
        type: 'select',
        label: 'Posição',
        defaultValue: 'center',
        options: [
          { label: 'Centro', value: 'center' },
          { label: 'Topo', value: 'top' },
          { label: 'Baixo', value: 'bottom' },
          { label: 'Esquerda', value: 'left' },
          { label: 'Direita', value: 'right' },
        ],
      },
      rounded: {
        type: 'select',
        label: 'Bordas',
        defaultValue: 'none',
        options: [
          { label: 'Nenhum', value: 'none' },
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
          { label: 'Círculo', value: 'full' },
        ],
      },
      shadow: {
        type: 'select',
        label: 'Sombra',
        defaultValue: 'none',
        options: [
          { label: 'Nenhuma', value: 'none' },
          { label: 'Pequena', value: 'sm' },
          { label: 'Média', value: 'md' },
          { label: 'Grande', value: 'lg' },
        ],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'Button',
    label: 'Botão',
    category: 'content',
    icon: 'MousePointerClick',
    defaultProps: {
      text: 'Clique Aqui',
      url: '#',
      variant: 'primary',
      size: 'md',
      alignment: 'left',
      fontFamily: 'inherit',
      fontWeight: 'semibold',
      backgroundColor: '',
      textColor: '',
      borderRadius: 'md',
      hoverBgColor: '',
      hoverTextColor: '',
      borderColor: '',
      hoverBorderColor: '',
    },
    propsSchema: {
      text: {
        type: 'string',
        label: 'Texto',
        defaultValue: 'Clique Aqui',
      },
      url: {
        type: 'string',
        label: 'Link',
        defaultValue: '#',
      },
      alignment: {
        type: 'select',
        label: 'Alinhamento',
        defaultValue: 'left',
        options: [
          { label: 'Esquerda', value: 'left' },
          { label: 'Centro', value: 'center' },
          { label: 'Direita', value: 'right' },
        ],
      },
      variant: {
        type: 'select',
        label: 'Estilo',
        defaultValue: 'primary',
        options: [
          { label: 'Primário', value: 'primary' },
          { label: 'Secundário', value: 'secondary' },
          { label: 'Contorno', value: 'outline' },
          { label: 'Fantasma', value: 'ghost' },
        ],
      },
      size: {
        type: 'select',
        label: 'Tamanho',
        defaultValue: 'md',
        options: [
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
        ],
      },
      fontFamily: {
        type: 'select',
        label: 'Fonte',
        defaultValue: 'inherit',
        options: [
          { label: 'Padrão do tema', value: 'inherit' },
          { label: 'Sans-serif', value: 'system-ui, sans-serif' },
          { label: 'Serif', value: 'Georgia, serif' },
          { label: 'Inter', value: 'Inter, sans-serif' },
          { label: 'Roboto', value: 'Roboto, sans-serif' },
        ],
      },
      fontWeight: {
        type: 'select',
        label: 'Peso da Fonte',
        defaultValue: 'semibold',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Médio', value: '500' },
          { label: 'Semi-negrito', value: 'semibold' },
          { label: 'Negrito', value: 'bold' },
        ],
      },
      backgroundColor: {
        type: 'color',
        label: 'Cor de Fundo',
      },
      textColor: {
        type: 'color',
        label: 'Cor do Texto',
      },
      hoverBgColor: {
        type: 'color',
        label: 'Cor de Fundo (Hover)',
      },
      hoverTextColor: {
        type: 'color',
        label: 'Cor do Texto (Hover)',
      },
      borderColor: {
        type: 'color',
        label: 'Cor da Borda',
      },
      hoverBorderColor: {
        type: 'color',
        label: 'Cor da Borda (Hover)',
      },
      borderRadius: {
        type: 'select',
        label: 'Bordas',
        defaultValue: 'md',
        options: [
          { label: 'Nenhum', value: 'none' },
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
          { label: 'Completo', value: 'full' },
        ],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'FAQ',
    label: 'Perguntas Frequentes',
    category: 'content',
    icon: 'HelpCircle',
    defaultProps: {
      title: 'Perguntas Frequentes',
      items: [
        { question: 'Como faço para comprar?', answer: 'Adicione produtos ao carrinho e finalize o pedido.' },
        { question: 'Qual o prazo de entrega?', answer: 'O prazo varia conforme a região.' },
      ],
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Perguntas Frequentes',
      },
      titleAlign: {
        type: 'select',
        label: 'Alinhamento do título',
        options: [
          { value: 'left', label: 'Esquerda' },
          { value: 'center', label: 'Centro' },
          { value: 'right', label: 'Direita' },
        ],
        defaultValue: 'left',
      },
      items: {
        type: 'array',
        label: 'Perguntas',
        defaultValue: [],
      },
      allowMultiple: {
        type: 'boolean',
        label: 'Permitir múltiplas abertas',
        defaultValue: false,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'Testimonials',
    label: 'Depoimentos',
    category: 'content',
    icon: 'MessageCircle',
    defaultProps: {
      title: 'O que dizem nossos clientes',
      items: [
        { name: 'Maria', text: 'Ótima experiência de compra!', rating: 5 },
        { name: 'João', text: 'Produtos de qualidade e entrega rápida.', rating: 5 },
      ],
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'O que dizem nossos clientes',
      },
      items: {
        type: 'array',
        label: 'Depoimentos',
        defaultValue: [],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'FeatureList',
    label: 'Lista de Features',
    category: 'content',
    icon: 'ListChecks',
    defaultProps: {
      title: '',
      subtitle: '',
      items: [
        { id: '1', icon: 'Check', text: 'Feature principal do produto' },
        { id: '2', icon: 'Check', text: 'Outro benefício importante' },
        { id: '3', icon: 'Check', text: 'Mais uma característica' },
      ],
      iconColor: '#22c55e',
      textColor: '',
      showButton: false,
      buttonText: 'Saiba mais',
      buttonUrl: '#',
      backgroundColor: 'transparent',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: '',
      },
      subtitle: {
        type: 'string',
        label: 'Subtítulo',
        defaultValue: '',
      },
      items: {
        type: 'array',
        label: 'Features',
        defaultValue: [],
      },
      iconColor: {
        type: 'color',
        label: 'Cor dos Ícones',
        defaultValue: '#22c55e',
      },
      textColor: {
        type: 'color',
        label: 'Cor do Texto',
        placeholder: 'Padrão do tema',
      },
      backgroundColor: {
        type: 'color',
        label: 'Cor de Fundo',
        defaultValue: 'transparent',
      },
      showButton: {
        type: 'boolean',
        label: 'Mostrar Botão',
        defaultValue: false,
      },
      buttonText: {
        type: 'string',
        label: 'Texto do Botão',
        defaultValue: 'Saiba mais',
      },
      buttonUrl: {
        type: 'string',
        label: 'Link do Botão',
        defaultValue: '#',
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'ContentColumns',
    label: 'Conteúdo em Colunas',
    category: 'content',
    icon: 'Columns',
    defaultProps: {
      title: 'Título da Seção',
      subtitle: '',
      content: '',
      imageDesktop: '',
      imageMobile: '',
      imagePosition: 'left',
      features: [],
      iconColor: '#22c55e',
      showButton: false,
      buttonText: 'Saiba mais',
      buttonUrl: '#',
      backgroundColor: 'transparent',
      textColor: '',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Título da Seção',
      },
      subtitle: {
        type: 'string',
        label: 'Subtítulo',
        defaultValue: '',
      },
      content: {
        type: 'richtext',
        label: 'Conteúdo',
        defaultValue: '',
      },
      imageDesktop: {
        type: 'image',
        label: 'Imagem Desktop',
      },
      imageMobile: {
        type: 'image',
        label: 'Imagem Mobile',
      },
      imagePosition: {
        type: 'select',
        label: 'Posição da Imagem',
        defaultValue: 'left',
        options: [
          { label: 'Esquerda', value: 'left' },
          { label: 'Direita', value: 'right' },
        ],
      },
      features: {
        type: 'array',
        label: 'Features',
        defaultValue: [],
      },
      iconColor: {
        type: 'color',
        label: 'Cor dos Ícones',
        defaultValue: '#22c55e',
      },
      showButton: {
        type: 'boolean',
        label: 'Mostrar Botão',
        defaultValue: false,
      },
      buttonText: {
        type: 'string',
        label: 'Texto do Botão',
        defaultValue: 'Saiba mais',
      },
      buttonUrl: {
        type: 'string',
        label: 'Link do Botão',
        defaultValue: '#',
      },
      backgroundColor: {
        type: 'color',
        label: 'Cor de Fundo',
        defaultValue: 'transparent',
      },
      textColor: {
        type: 'color',
        label: 'Cor do Texto',
        placeholder: 'Padrão do tema',
      },
    },
    canHaveChildren: false,
  },

  // ========== ECOMMERCE BLOCKS ==========
  {
    type: 'CategoryList',
    label: 'Lista de Categorias',
    category: 'ecommerce',
    icon: 'FolderTree',
    defaultProps: {
      title: 'Categorias',
      layout: 'grid',
      columns: 4,
      showDescription: false,
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Categorias',
      },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'grid',
        options: [
          { label: 'Grade', value: 'grid' },
          { label: 'Lista', value: 'list' },
          { label: 'Carrossel', value: 'carousel' },
        ],
      },
      columns: {
        type: 'select',
        label: 'Colunas',
        defaultValue: '4',
        options: [
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
          { label: '6', value: '6' },
        ],
      },
      showDescription: {
        type: 'boolean',
        label: 'Mostrar Descrição',
        defaultValue: false,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'ProductGrid',
    label: 'Vitrine de Produtos',
    category: 'ecommerce',
    icon: 'LayoutGrid',
    defaultProps: {
      title: 'Produtos',
      source: 'featured',
      categoryId: '',
      columns: 4,
      limit: 8,
      showPrice: true,
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Produtos',
      },
      source: {
        type: 'select',
        label: 'Fonte',
        defaultValue: 'featured',
        options: [
          { label: 'Destaques', value: 'featured' },
          { label: 'Mais Vendidos', value: 'bestsellers' },
          { label: 'Novidades', value: 'newest' },
          { label: 'Categoria', value: 'category' },
        ],
      },
      categoryId: {
        type: 'category',
        label: 'Categoria (se fonte = Categoria)',
        placeholder: 'Selecione uma categoria',
      },
      columns: {
        type: 'select',
        label: 'Colunas',
        defaultValue: '4',
        options: [
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      limit: {
        type: 'number',
        label: 'Limite de Produtos',
        defaultValue: 8,
        min: 1,
        max: 24,
      },
      showPrice: {
        type: 'boolean',
        label: 'Mostrar Preço',
        defaultValue: true,
      },
    },
    canHaveChildren: false,
  },
  // CategoryPageLayout - Listagem de produtos de categoria com filtros (REGRAS.md)
  // NOTA: Este bloco NÃO possui propsSchema pois as configurações de categoria
  // são feitas via "Configurações do tema > Categoria" (CategorySettingsPanel)
  // e não via props do bloco. Isso evita que apareça painel de edição ao clicar.
  {
    type: 'CategoryPageLayout',
    label: 'Listagem de Categoria',
    category: 'ecommerce',
    icon: 'LayoutList',
    defaultProps: {
      showFilters: true,
      columns: 4,
      limit: 24,
    },
    // propsSchema vazio - configurações via CategorySettingsPanel
    propsSchema: {},
    canHaveChildren: false,
    isRemovable: false, // REGRAS.md: estrutura obrigatória
  },
  {
    type: 'ProductCarousel',
    label: 'Carrossel de Produtos',
    category: 'ecommerce',
    icon: 'Carousel',
    defaultProps: {
      title: 'Produtos em Destaque',
      source: 'featured',
      categoryId: '',
      limit: 8,
      showPrice: true,
      showButton: true,
      buttonText: 'Ver produto',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Produtos em Destaque',
      },
      source: {
        type: 'select',
        label: 'Fonte',
        defaultValue: 'featured',
        options: [
          { label: 'Destaques', value: 'featured' },
          { label: 'Novidades', value: 'newest' },
          { label: 'Todos', value: 'all' },
          { label: 'Categoria', value: 'category' },
        ],
      },
      categoryId: {
        type: 'category',
        label: 'Categoria (se fonte = Categoria)',
        placeholder: 'Selecione uma categoria',
      },
      limit: {
        type: 'number',
        label: 'Limite de Produtos',
        defaultValue: 8,
        min: 4,
        max: 20,
      },
      showPrice: {
        type: 'boolean',
        label: 'Mostrar Preço',
        defaultValue: true,
      },
      showButton: {
        type: 'boolean',
        label: 'Mostrar Botão',
        defaultValue: true,
      },
      buttonText: {
        type: 'string',
        label: 'Texto do Botão',
        defaultValue: 'Ver produto',
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'FeaturedProducts',
    label: 'Produtos Selecionados',
    category: 'ecommerce',
    icon: 'Star',
    defaultProps: {
      title: 'Produtos em Destaque',
      productIds: [],
      limit: 4,
      columns: 4,
      showPrice: true,
      showButton: true,
      buttonText: 'Ver produto',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Produtos em Destaque',
      },
      productIds: {
        type: 'productMultiSelect',
        label: 'Produtos',
      },
      limit: {
        type: 'number',
        label: 'Limite de Produtos',
        defaultValue: 4,
        min: 1,
        max: 12,
      },
      columns: {
        type: 'select',
        label: 'Colunas',
        defaultValue: '4',
        options: [
          { label: '2', value: '2' },
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      showPrice: {
        type: 'boolean',
        label: 'Mostrar Preço',
        defaultValue: true,
      },
      showButton: {
        type: 'boolean',
        label: 'Mostrar Botão',
        defaultValue: true,
      },
      buttonText: {
        type: 'string',
        label: 'Texto do Botão',
        defaultValue: 'Ver produto',
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'ProductCard',
    label: 'Card de Produto',
    category: 'ecommerce',
    icon: 'Package',
    defaultProps: {
      productId: '',
      showPrice: true,
      showButton: true,
    },
    propsSchema: {
      productId: {
        type: 'product',
        label: 'Produto',
        placeholder: 'Selecione um produto',
      },
      showPrice: {
        type: 'boolean',
        label: 'Mostrar Preço',
        defaultValue: true,
      },
      showButton: {
        type: 'boolean',
        label: 'Mostrar Botão',
        defaultValue: true,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'ProductDetails',
    label: 'Detalhes do Produto',
    category: 'ecommerce',
    icon: 'ShoppingBag',
    defaultProps: {
      exampleProductId: '',
      showGallery: true,
      showDescription: true,
      showVariants: true,
      showStock: true,
    },
    propsSchema: {
      exampleProductId: {
        type: 'product',
        label: 'Produto de Exemplo',
        placeholder: 'Para pré-visualização no editor',
      },
      showGallery: {
        type: 'boolean',
        label: 'Mostrar Galeria',
        defaultValue: true,
      },
      showDescription: {
        type: 'boolean',
        label: 'Mostrar Descrição',
        defaultValue: true,
      },
      showVariants: {
        type: 'boolean',
        label: 'Mostrar variações',
        defaultValue: true,
      },
      showStock: {
        type: 'boolean',
        label: 'Mostrar Estoque',
        defaultValue: true,
      },
    },
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'CartSummary',
    label: 'Resumo do Carrinho',
    category: 'ecommerce',
    icon: 'ShoppingCart',
    defaultProps: {
      showThumbnails: true,
      showQuantityControls: true,
    },
    propsSchema: {
      showThumbnails: {
        type: 'boolean',
        label: 'Mostrar Miniaturas',
        defaultValue: true,
      },
      showQuantityControls: {
        type: 'boolean',
        label: 'Controles de Quantidade',
        defaultValue: true,
      },
    },
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'CheckoutSteps',
    label: 'Etapas do Checkout',
    category: 'ecommerce',
    icon: 'ListChecks',
    defaultProps: {
      steps: ['Identificação', 'Entrega', 'Pagamento', 'Confirmação'],
    },
    propsSchema: {
      steps: {
        type: 'array',
        label: 'Etapas',
        defaultValue: ['Identificação', 'Entrega', 'Pagamento', 'Confirmação'],
      },
    },
    canHaveChildren: false,
    isRemovable: false,
  },

  // ========== ESSENTIAL BLOCKS (8 novos) ==========
  {
    type: 'HeroBanner',
    label: 'Carrossel de Banners',
    category: 'media',
    icon: 'Image',
    defaultProps: {
      slides: [],
      autoplaySeconds: 5,
      bannerWidth: 'full',
      showArrows: true,
      showDots: true,
    },
    propsSchema: {
      slides: {
        type: 'array',
        label: 'Slides do Carrossel',
        defaultValue: [],
        helpText: 'Adicione slides com imagens para Desktop e Mobile',
      },
      autoplaySeconds: {
        type: 'number',
        label: 'Tempo de Autoplay (segundos)',
        defaultValue: 5,
        min: 0,
        max: 30,
      },
      bannerWidth: {
        type: 'select',
        label: 'Largura do Banner',
        defaultValue: 'full',
        options: [
          { label: 'Largura Total', value: 'full' },
          { label: 'Contido', value: 'contained' },
        ],
      },
      showArrows: {
        type: 'boolean',
        label: 'Mostrar Setas',
        defaultValue: true,
      },
      showDots: {
        type: 'boolean',
        label: 'Mostrar Indicadores',
        defaultValue: true,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'CollectionSection',
    label: 'Categoria/Coleção',
    category: 'ecommerce',
    icon: 'LayoutGrid',
    defaultProps: {
      title: 'Coleção',
      categoryId: '',
      displayStyle: 'grid',
      limit: 8,
      columns: 4,
      mobileColumns: 2,
      showViewAll: true,
      viewAllText: 'Ver todos',
      showPrice: true,
      showButton: true,
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título da Seção',
        defaultValue: 'Coleção',
      },
      categoryId: {
        type: 'category',
        label: 'Categoria',
        placeholder: 'Selecione uma categoria',
      },
      displayStyle: {
        type: 'select',
        label: 'Estilo de Exibição',
        defaultValue: 'grid',
        options: [
          { label: 'Grade', value: 'grid' },
          { label: 'Carrossel', value: 'carousel' },
        ],
      },
      limit: {
        type: 'number',
        label: 'Quantidade de Produtos',
        defaultValue: 8,
        min: 4,
        max: 24,
      },
      columns: {
        type: 'select',
        label: 'Colunas (Desktop)',
        defaultValue: '4',
        options: [
          { label: '3', value: '3' },
          { label: '4', value: '4' },
          { label: '5', value: '5' },
        ],
      },
      mobileColumns: {
        type: 'select',
        label: 'Colunas (Mobile)',
        defaultValue: '2',
        options: [
          { label: '1', value: '1' },
          { label: '2', value: '2' },
        ],
      },
      showViewAll: {
        type: 'boolean',
        label: 'Mostrar "Ver todos"',
        defaultValue: true,
      },
      viewAllText: {
        type: 'string',
        label: 'Texto do Link',
        defaultValue: 'Ver todos',
      },
      showPrice: {
        type: 'boolean',
        label: 'Mostrar Preço',
        defaultValue: true,
      },
      showButton: {
        type: 'boolean',
        label: 'Mostrar Botão',
        defaultValue: true,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'InfoHighlights',
    label: 'Benefícios da Loja',
    category: 'content',
    icon: 'Award',
    defaultProps: {
      items: [
        { id: '1', icon: 'Truck', title: 'Frete Grátis', description: 'Em compras acima de R$199' },
        { id: '2', icon: 'CreditCard', title: 'Parcelamento', description: 'Em até 12x sem juros' },
        { id: '3', icon: 'Shield', title: 'Compra Segura', description: 'Seus dados protegidos' },
      ],
      layout: 'horizontal',
      iconColor: '',
      textColor: '',
    },
    propsSchema: {
      items: {
        type: 'array',
        label: 'Itens',
        defaultValue: [],
      },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'horizontal',
        options: [
          { label: 'Horizontal', value: 'horizontal' },
          { label: 'Vertical', value: 'vertical' },
        ],
      },
      iconColor: {
        type: 'color',
        label: 'Cor dos Ícones',
        placeholder: 'Padrão do tema',
      },
      textColor: {
        type: 'color',
        label: 'Cor do Texto',
        placeholder: 'Padrão do tema',
      },
    },
    canHaveChildren: false,
  },
  {
    // REGRAS.md linha 77: Banner configurado SOMENTE no menu Categorias
    // Sem opções de edição no builder - propsSchema vazio = sem painel direito
    type: 'CategoryBanner',
    label: 'Banner da Categoria',
    category: 'ecommerce',
    icon: 'Image',
    defaultProps: {},
    propsSchema: {},
    canHaveChildren: false,
  },
  {
    type: 'BannerProducts',
    label: 'Banner + Produtos',
    category: 'ecommerce',
    icon: 'Layers',
    defaultProps: {
      title: 'Oferta Especial',
      description: '',
      imageDesktop: '',
      imageMobile: '',
      source: 'manual',
      productIds: [],
      categoryId: '',
      limit: 4,
      showCta: false,
      ctaText: 'Ver mais',
      ctaUrl: '',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Oferta Especial',
      },
      description: {
        type: 'string',
        label: 'Descrição',
        placeholder: 'Descrição opcional',
      },
      imageDesktop: {
        type: 'image',
        label: 'Imagem Desktop',
        placeholder: 'URL da imagem desktop',
        helpText: 'Recomendado: 600×400px (proporção 3:2)',
      },
      imageMobile: {
        type: 'image',
        label: 'Imagem Mobile',
        placeholder: 'URL da imagem mobile (opcional)',
        helpText: 'Recomendado: 400×500px (proporção 4:5)',
      },
      source: {
        type: 'select',
        label: 'Fonte dos Produtos',
        defaultValue: 'manual',
        options: [
          { label: 'Selecionados (manual)', value: 'manual' },
          { label: 'Categoria', value: 'category' },
        ],
      },
      productIds: {
        type: 'productMultiSelect',
        label: 'Produtos',
        showWhen: { source: 'manual' },
      },
      categoryId: {
        type: 'category',
        label: 'Categoria',
        placeholder: 'Selecione uma categoria',
        showWhen: { source: 'category' },
      },
      limit: {
        type: 'number',
        label: 'Limite de Produtos',
        defaultValue: 4,
        min: 2,
        max: 8,
      },
      showCta: {
        type: 'boolean',
        label: 'Mostrar CTA',
        defaultValue: false,
      },
      ctaText: {
        type: 'string',
        label: 'Texto do CTA',
        defaultValue: 'Ver mais',
      },
      ctaUrl: {
        type: 'string',
        label: 'URL do CTA',
        placeholder: 'Link do botão',
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'YouTubeVideo',
    label: 'Vídeo (YouTube)',
    category: 'media',
    icon: 'Youtube',
    defaultProps: {
      title: '',
      youtubeUrl: '',
      widthPreset: 'lg',
      aspectRatio: '16:9',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título (opcional)',
        placeholder: 'Título da seção',
      },
      youtubeUrl: {
        type: 'string',
        label: 'URL do YouTube',
        placeholder: 'https://www.youtube.com/watch?v=...',
      },
      widthPreset: {
        type: 'select',
        label: 'Largura do vídeo',
        defaultValue: 'lg',
        options: [
          { label: 'Pequeno (sm)', value: 'sm' },
          { label: 'Médio (md)', value: 'md' },
          { label: 'Grande (lg)', value: 'lg' },
          { label: 'Extra grande (xl)', value: 'xl' },
          { label: 'Largura total', value: 'full' },
        ],
      },
      aspectRatio: {
        type: 'select',
        label: 'Proporção',
        defaultValue: '16:9',
        options: [
          { label: '16:9 (Horizontal)', value: '16:9' },
          { label: '4:3 (Clássico)', value: '4:3' },
          { label: '1:1 (Quadrado)', value: '1:1' },
        ],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'VideoCarousel',
    label: 'Carrossel de Vídeos',
    category: 'media',
    icon: 'PlayCircle',
    defaultProps: {
      title: '',
      videos: [],
      videosJson: '',
      showControls: true,
      aspectRatio: '16:9',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título (opcional)',
        placeholder: 'Nossos Vídeos',
      },
      videos: {
        type: 'array',
        label: 'Vídeos',
        helpText: 'YouTube: use "url". Upload: use "videoDesktop" e "videoMobile" (ou só videoDesktop)',
      },
      videosJson: {
        type: 'textarea',
        label: 'URLs dos Vídeos (alternativo)',
        placeholder: 'https://youtube.com/watch?v=abc123\nhttps://youtu.be/xyz456',
        helpText: 'Cole URLs do YouTube (uma por linha) ou JSON de vídeos',
      },
      showControls: {
        type: 'boolean',
        label: 'Mostrar setas de navegação',
        defaultValue: true,
      },
      aspectRatio: {
        type: 'select',
        label: 'Proporção',
        defaultValue: '16:9',
        options: [
          { label: '16:9 (Horizontal)', value: '16:9' },
          { label: '4:3 (Clássico)', value: '4:3' },
          { label: '1:1 (Quadrado)', value: '1:1' },
          { label: '9:16 (Vertical)', value: '9:16' },
        ],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'VideoUpload',
    label: 'Vídeo (Upload)',
    category: 'media',
    icon: 'Video',
    defaultProps: {
      videoDesktop: '',
      videoMobile: '',
      controls: true,
      autoplay: false,
      loop: false,
      muted: false,
      aspectRatio: 'auto',
      aspectRatioCustom: '',
      objectFit: 'contain',
    },
    propsSchema: {
      videoDesktop: {
        type: 'video',
        label: 'Vídeo Desktop',
        helpText: 'MP4, WEBM ou MOV',
      },
      videoMobile: {
        type: 'video',
        label: 'Vídeo Mobile',
        placeholder: 'Opcional - usa Desktop se vazio',
      },
      aspectRatio: {
        type: 'select',
        label: 'Proporção',
        defaultValue: 'auto',
        options: [
          { label: 'Auto (detectar)', value: 'auto' },
          { label: '16:9 (Horizontal)', value: '16/9' },
          { label: '9:16 (Vertical)', value: '9/16' },
          { label: '4:3 (Clássico)', value: '4/3' },
          { label: '1:1 (Quadrado)', value: '1/1' },
          { label: '4:5 (Instagram)', value: '4/5' },
          { label: '21:9 (Ultrawide)', value: '21/9' },
          { label: 'Personalizado', value: 'custom' },
        ],
      },
      aspectRatioCustom: {
        type: 'string',
        label: 'Proporção Personalizada',
        placeholder: 'Ex: 3/4 ou 1.5',
        helpText: 'Use formato X/Y ou número decimal',
      },
      objectFit: {
        type: 'select',
        label: 'Encaixe',
        defaultValue: 'contain',
        options: [
          { label: 'Mostrar inteiro (contain)', value: 'contain' },
          { label: 'Preencher (cover)', value: 'cover' },
          { label: 'Esticar (fill)', value: 'fill' },
        ],
      },
      controls: {
        type: 'boolean',
        label: 'Mostrar Controles',
        defaultValue: true,
      },
      autoplay: {
        type: 'boolean',
        label: 'Reprodução Automática',
        defaultValue: false,
      },
      loop: {
        type: 'boolean',
        label: 'Repetir',
        defaultValue: false,
      },
      muted: {
        type: 'boolean',
        label: 'Sem Som (Mudo)',
        defaultValue: false,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'Reviews',
    label: 'Avaliações',
    category: 'content',
    icon: 'Star',
    defaultProps: {
      title: 'O que nossos clientes dizem',
      reviews: [
        { name: 'Maria S.', rating: 5, text: 'Produto excelente, entrega rápida!' },
        { name: 'João P.', rating: 5, text: 'Superou minhas expectativas.' },
      ],
      visibleCount: 3,
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'O que nossos clientes dizem',
      },
      reviews: {
        type: 'array',
        label: 'Avaliações',
        defaultValue: [],
      },
      visibleCount: {
        type: 'number',
        label: 'Quantidade Visível',
        defaultValue: 3,
        min: 1,
        max: 10,
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'FeaturedCategories',
    label: 'Categorias em Destaque',
    category: 'ecommerce',
    icon: 'Grid3x3',
    defaultProps: {
      title: 'Categorias',
      items: [],
      showName: true,
      mobileStyle: 'grid',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        defaultValue: 'Categorias',
      },
      items: {
        type: 'categoryMultiSelect',
        label: 'Categorias',
        max: 12,
      },
      showName: {
        type: 'boolean',
        label: 'Exibir Nome',
        defaultValue: true,
      },
      mobileStyle: {
        type: 'select',
        label: 'Estilo Mobile',
        defaultValue: 'grid',
        options: [
          { label: 'Grade', value: 'grid' },
          { label: 'Carrossel', value: 'carousel' },
        ],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'TextBanners',
    label: 'Texto + Banners',
    category: 'content',
    icon: 'FileText',
    defaultProps: {
      title: 'Título legal',
      text: 'Escreva seu texto aqui, falando um pouco sobre sua marca, produto, empresa ou promoção. Solte sua imaginação!',
      imageDesktop1: '',
      imageMobile1: '',
      imageDesktop2: '',
      imageMobile2: '',
      ctaEnabled: true,
      ctaText: 'Saiba mais',
      ctaUrl: '#',
      ctaBgColor: '',
      ctaTextColor: '',
      layout: 'text-left',
    },
    propsSchema: {
      title: {
        type: 'string',
        label: 'Título',
        placeholder: 'Título da seção',
      },
      text: {
        type: 'textarea',
        label: 'Texto',
        placeholder: 'Conteúdo do texto',
      },
      imageDesktop1: {
        type: 'image',
        label: 'Imagem 1 (Desktop)',
        placeholder: 'URL da imagem desktop',
        helpText: 'Recomendado: 600×800px (proporção 3:4)',
      },
      imageMobile1: {
        type: 'image',
        label: 'Imagem 1 (Mobile)',
        placeholder: 'URL da imagem mobile (opcional)',
      },
      imageDesktop2: {
        type: 'image',
        label: 'Imagem 2 (Desktop)',
        placeholder: 'URL da imagem desktop',
        helpText: 'Recomendado: 600×800px (proporção 3:4)',
      },
      imageMobile2: {
        type: 'image',
        label: 'Imagem 2 (Mobile)',
        placeholder: 'URL da imagem mobile (opcional)',
      },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'text-left',
        options: [
          { label: 'Texto à esquerda', value: 'text-left' },
          { label: 'Texto à direita', value: 'text-right' },
        ],
      },
      ctaEnabled: {
        type: 'boolean',
        label: 'Mostrar CTA',
        defaultValue: true,
      },
      ctaText: {
        type: 'string',
        label: 'Texto do CTA',
        defaultValue: 'Saiba mais',
      },
      ctaUrl: {
        type: 'string',
        label: 'URL do CTA',
        placeholder: 'Link do botão',
      },
      ctaBgColor: {
        type: 'color',
        label: 'Cor de Fundo do CTA',
        placeholder: 'Padrão do tema',
      },
      ctaTextColor: {
        type: 'color',
        label: 'Cor do Texto do CTA',
        placeholder: 'Padrão do tema',
      },
    },
    canHaveChildren: false,
  },
  // ========== ESSENTIAL ECOMMERCE BLOCKS (non-removable) ==========
  // ========== SYSTEM BLOCKS (Config via Theme Settings > Pages only) ==========
  // NOTE: propsSchema removed - all settings managed in Configurações do tema > Páginas
  {
    type: 'Cart',
    label: 'Carrinho',
    category: 'ecommerce',
    icon: 'ShoppingCart',
    defaultProps: {},
    propsSchema: {}, // Settings managed in Theme Settings > Pages > Carrinho
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'Checkout',
    label: 'Checkout',
    category: 'ecommerce',
    icon: 'CreditCard',
    defaultProps: {},
    propsSchema: {}, // Settings managed in Theme Settings > Pages > Checkout
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'ThankYou',
    label: 'Confirmação de Pedido',
    category: 'ecommerce',
    icon: 'CheckCircle',
    defaultProps: {},
    propsSchema: {}, // Settings managed in Theme Settings > Pages > Obrigado
    canHaveChildren: false,
    isRemovable: false,
  },
  // ========== ACCOUNT BLOCKS (essential, non-removable) ==========
  {
    type: 'AccountHub',
    label: 'Hub da Conta',
    category: 'ecommerce',
    icon: 'User',
    defaultProps: {},
    propsSchema: {},
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'OrdersList',
    label: 'Lista de Pedidos',
    category: 'ecommerce',
    icon: 'Package',
    defaultProps: {},
    propsSchema: {},
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'OrderDetail',
    label: 'Detalhe do Pedido',
    category: 'ecommerce',
    icon: 'FileText',
    defaultProps: {},
    propsSchema: {},
    canHaveChildren: false,
    isRemovable: false,
  },
  // ========== SYSTEM BLOCKS (Rastreio, Blog) - Config via Theme Settings ==========
  {
    type: 'TrackingLookup',
    label: 'Rastrear Pedido',
    category: 'ecommerce',
    icon: 'Package',
    defaultProps: {},
    propsSchema: {}, // Settings managed in Theme Settings > Pages > Rastreio
    canHaveChildren: false,
    isRemovable: false,
  },
  {
    type: 'BlogListing',
    label: 'Listagem do Blog',
    category: 'content',
    icon: 'FileText',
    defaultProps: {},
    propsSchema: {}, // Settings managed in Theme Settings > Pages > Blog
    canHaveChildren: false,
    isRemovable: false,
  },
  // ========== CUSTOM BLOCK (Imported Content) ==========
  {
    type: 'CustomBlock',
    label: 'Bloco Importado',
    category: 'content',
    icon: 'Code',
    defaultProps: {
      customBlockId: '',
      htmlContent: '',
      cssContent: '',
      blockName: 'Conteúdo Importado',
    },
    propsSchema: {
      customBlockId: {
        type: 'string',
        label: 'ID do Bloco (DB)',
        placeholder: 'UUID do custom_blocks',
      },
      htmlContent: {
        type: 'textarea',
        label: 'HTML (fallback)',
        placeholder: 'HTML direto se não usar ID',
      },
      cssContent: {
        type: 'textarea',
        label: 'CSS (fallback)',
        placeholder: 'CSS direto se não usar ID',
      },
      blockName: {
        type: 'string',
        label: 'Nome do Bloco',
        defaultValue: 'Conteúdo Importado',
      },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  // ========== HTML SECTION (Manual HTML/CSS) ==========
  {
    type: 'HTMLSection',
    label: 'Bloco Html',
    category: 'layout',
    icon: 'FileCode',
    defaultProps: {
      htmlContent: '<div style="padding: 40px; text-align: center; background: #f0f0f0;">\n  <h2>Seção HTML Customizada</h2>\n  <p>Edite o HTML e CSS nas propriedades do bloco.</p>\n</div>',
      cssContent: '',
      blockName: 'Seção HTML',
      baseUrl: '',
    },
    propsSchema: {
      htmlContent: {
        type: 'textarea',
        label: 'Código HTML',
        placeholder: '<div>Seu HTML aqui...</div>',
      },
      cssContent: {
        type: 'textarea',
        label: 'Código CSS',
        placeholder: '.minha-classe { color: red; }',
      },
      blockName: {
        type: 'string',
        label: 'Nome do Bloco',
        defaultValue: 'Bloco Html',
      },
      baseUrl: {
        type: 'string',
        label: 'URL Base (para imagens relativas)',
        placeholder: 'https://exemplo.com/',
      },
    },
    canHaveChildren: false,
    isRemovable: true,
  },

  // ========== NEW BLOCKS (6 novos) ==========
  {
    type: 'StepsTimeline',
    label: 'Passos / Timeline',
    category: 'content',
    icon: 'ListOrdered',
    defaultProps: {
      title: 'Como Funciona',
      subtitle: '',
      steps: [
        { number: 1, title: 'Passo 1', description: 'Descrição do primeiro passo' },
        { number: 2, title: 'Passo 2', description: 'Descrição do segundo passo' },
        { number: 3, title: 'Passo 3', description: 'Descrição do terceiro passo' },
      ],
      layout: 'horizontal',
      accentColor: '#6366f1',
      showNumbers: true,
      backgroundColor: 'transparent',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      steps: { type: 'array', label: 'Passos' },
      layout: { type: 'select', label: 'Layout', options: [{ label: 'Horizontal', value: 'horizontal' }, { label: 'Vertical', value: 'vertical' }] },
      accentColor: { type: 'color', label: 'Cor de Destaque' },
      showNumbers: { type: 'boolean', label: 'Mostrar Números' },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'CountdownTimer',
    label: 'Contador Regressivo',
    category: 'content',
    icon: 'Timer',
    defaultProps: {
      title: 'Oferta por tempo limitado',
      subtitle: '',
      endDate: '',
      showDays: true,
      showHours: true,
      showMinutes: true,
      showSeconds: true,
      backgroundColor: '#dc2626',
      textColor: '#ffffff',
      expiredMessage: 'Oferta encerrada',
      buttonText: '',
      buttonUrl: '',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      endDate: { type: 'string', label: 'Data de Término (ISO)' },
      showDays: { type: 'boolean', label: 'Mostrar Dias' },
      showHours: { type: 'boolean', label: 'Mostrar Horas' },
      showMinutes: { type: 'boolean', label: 'Mostrar Minutos' },
      showSeconds: { type: 'boolean', label: 'Mostrar Segundos' },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
      textColor: { type: 'color', label: 'Cor do Texto' },
      expiredMessage: { type: 'string', label: 'Mensagem de Expirado' },
      buttonText: { type: 'string', label: 'Texto do Botão' },
      buttonUrl: { type: 'string', label: 'URL do Botão' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'LogosCarousel',
    label: 'Logos / Parceiros',
    category: 'content',
    icon: 'Building2',
    defaultProps: {
      title: 'Nossos Parceiros',
      subtitle: '',
      logos: [],
      autoplay: true,
      grayscale: true,
      columns: 5,
      backgroundColor: 'transparent',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      logos: { type: 'array', label: 'Logos' },
      autoplay: { type: 'boolean', label: 'Autoplay' },
      grayscale: { type: 'boolean', label: 'Escala de Cinza' },
      columns: { type: 'select', label: 'Colunas', options: [{ label: '3', value: '3' }, { label: '4', value: '4' }, { label: '5', value: '5' }, { label: '6', value: '6' }] },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'StatsNumbers',
    label: 'Estatísticas',
    category: 'content',
    icon: 'BarChart3',
    defaultProps: {
      title: '',
      subtitle: '',
      items: [
        { number: '10k+', label: 'Clientes satisfeitos' },
        { number: '99%', label: 'Aprovação' },
        { number: '24h', label: 'Entrega' },
      ],
      layout: 'horizontal',
      animateNumbers: true,
      backgroundColor: 'transparent',
      accentColor: '#6366f1',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      items: { type: 'array', label: 'Estatísticas' },
      layout: { type: 'select', label: 'Layout', options: [{ label: 'Horizontal', value: 'horizontal' }, { label: 'Grid', value: 'grid' }] },
      animateNumbers: { type: 'boolean', label: 'Animar Números' },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
      accentColor: { type: 'color', label: 'Cor de Destaque' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'ImageGallery',
    label: 'Galeria de Imagens',
    category: 'media',
    icon: 'Images',
    defaultProps: {
      title: '',
      subtitle: '',
      images: [],
      columns: 3,
      gap: 'md',
      enableLightbox: true,
      aspectRatio: 'square',
      borderRadius: 8,
      backgroundColor: 'transparent',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      images: { type: 'array', label: 'Imagens' },
      columns: { type: 'select', label: 'Colunas', options: [{ label: '2', value: '2' }, { label: '3', value: '3' }, { label: '4', value: '4' }] },
      gap: { type: 'select', label: 'Espaçamento', options: [{ label: 'Pequeno', value: 'sm' }, { label: 'Médio', value: 'md' }, { label: 'Grande', value: 'lg' }] },
      enableLightbox: { type: 'boolean', label: 'Habilitar Lightbox' },
      aspectRatio: { type: 'select', label: 'Proporção', options: [{ label: 'Quadrado', value: 'square' }, { label: '4:3', value: '4:3' }, { label: '16:9', value: '16:9' }, { label: 'Auto', value: 'auto' }] },
      borderRadius: { type: 'number', label: 'Arredondamento (px)' },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'AccordionBlock',
    label: 'Acordeão',
    category: 'content',
    icon: 'ChevronDown',
    defaultProps: {
      title: '',
      subtitle: '',
      items: [
        { title: 'Item 1', content: 'Conteúdo do primeiro item' },
        { title: 'Item 2', content: 'Conteúdo do segundo item' },
      ],
      allowMultiple: false,
      defaultOpen: -1,
      variant: 'default',
      backgroundColor: 'transparent',
      accentColor: '#6366f1',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      items: { type: 'array', label: 'Itens' },
      allowMultiple: { type: 'boolean', label: 'Permitir Múltiplos Abertos' },
      defaultOpen: { type: 'number', label: 'Item Aberto por Padrão (-1 = nenhum)' },
      variant: { type: 'select', label: 'Estilo', options: [{ label: 'Padrão', value: 'default' }, { label: 'Separado', value: 'separated' }, { label: 'Com Borda', value: 'bordered' }] },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
      accentColor: { type: 'color', label: 'Cor de Destaque' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  // ========== MEDIA CAROUSEL BLOCKS ==========
  {
    type: 'VideoCarousel',
    label: 'Carrossel de Vídeos',
    category: 'media',
    icon: 'Film',
    defaultProps: {
      title: '',
      videos: [],
      autoplay: false,
      showControls: true,
      aspectRatio: '16:9',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      videos: { type: 'array', label: 'Vídeos', helpText: 'YouTube URLs ou vídeos via upload' },
      autoplay: { type: 'boolean', label: 'Autoplay' },
      showControls: { type: 'boolean', label: 'Mostrar Controles' },
      aspectRatio: { 
        type: 'select', 
        label: 'Proporção', 
        options: [
          { label: '16:9', value: '16:9' }, 
          { label: '4:3', value: '4:3' }, 
          { label: '1:1', value: '1:1' },
        ],
      },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'ImageCarousel',
    label: 'Carrossel de Imagens',
    category: 'media',
    icon: 'Images',
    defaultProps: {
      title: '',
      images: [],
      autoplay: false,
      autoplayInterval: 5,
      showArrows: true,
      showDots: true,
      enableLightbox: false,
      aspectRatio: '16:9',
      slidesPerView: 1,
      gap: 'md',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      images: { type: 'array', label: 'Imagens', helpText: 'Adicione imagens para Desktop e Mobile' },
      autoplay: { type: 'boolean', label: 'Autoplay' },
      autoplayInterval: { 
        type: 'number', 
        label: 'Intervalo de Autoplay (segundos)', 
        defaultValue: 5, 
        min: 1, 
        max: 30,
      },
      showArrows: { type: 'boolean', label: 'Mostrar Setas' },
      showDots: { type: 'boolean', label: 'Mostrar Indicadores' },
      enableLightbox: { type: 'boolean', label: 'Habilitar Lightbox' },
      aspectRatio: { 
        type: 'select', 
        label: 'Proporção', 
        options: [
          { label: '16:9', value: '16:9' }, 
          { label: '4:3', value: '4:3' }, 
          { label: '1:1', value: '1:1' },
          { label: '21:9', value: '21:9' },
          { label: 'Auto', value: 'auto' },
        ],
      },
      slidesPerView: { 
        type: 'select', 
        label: 'Slides por Visualização', 
        options: [
          { label: '1', value: '1' }, 
          { label: '2', value: '2' }, 
          { label: '3', value: '3' },
          { label: '4', value: '4' },
        ],
      },
      gap: { 
        type: 'select', 
        label: 'Espaçamento', 
        options: [
          { label: 'Pequeno', value: 'sm' }, 
          { label: 'Médio', value: 'md' }, 
          { label: 'Grande', value: 'lg' },
        ],
      },
    },
    canHaveChildren: false,
    isRemovable: true,
  },

  // ========== INTERACTIVE BLOCKS ==========
  {
    type: 'Newsletter',
    label: 'Newsletter',
    category: 'content',
    icon: 'Mail',
    defaultProps: {
      title: 'Receba nossas novidades',
      subtitle: 'Cadastre-se e receba ofertas exclusivas em primeira mão!',
      placeholder: 'Digite seu e-mail',
      buttonText: 'Inscrever-se',
      successMessage: 'Obrigado! Você foi inscrito com sucesso.',
      layout: 'horizontal',
      showIcon: true,
      showIncentive: false,
      incentiveText: '🎁 Ganhe 10% OFF na primeira compra!',
      backgroundColor: '',
      textColor: '',
      buttonBgColor: '',
      buttonTextColor: '',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título', defaultValue: 'Receba nossas novidades' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      placeholder: { type: 'string', label: 'Placeholder', defaultValue: 'Digite seu e-mail' },
      buttonText: { type: 'string', label: 'Texto do Botão', defaultValue: 'Inscrever-se' },
      successMessage: { type: 'string', label: 'Mensagem de Sucesso' },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'horizontal',
        options: [
          { label: 'Horizontal', value: 'horizontal' },
          { label: 'Vertical', value: 'vertical' },
          { label: 'Card', value: 'card' },
        ],
      },
      showIcon: { type: 'boolean', label: 'Mostrar Ícone', defaultValue: true },
      showIncentive: { type: 'boolean', label: 'Mostrar Incentivo', defaultValue: false },
      incentiveText: { type: 'string', label: 'Texto do Incentivo' },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
      textColor: { type: 'color', label: 'Cor do Texto' },
      buttonBgColor: { type: 'color', label: 'Cor do Botão' },
      buttonTextColor: { type: 'color', label: 'Cor do Texto do Botão' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'ContactForm',
    label: 'Formulário de Contato',
    category: 'content',
    icon: 'MessageSquare',
    defaultProps: {
      title: 'Entre em Contato',
      subtitle: 'Preencha o formulário abaixo e entraremos em contato em breve.',
      layout: 'simple',
      showName: true,
      showPhone: false,
      showSubject: true,
      nameLabel: 'Nome',
      emailLabel: 'E-mail',
      phoneLabel: 'Telefone',
      subjectLabel: 'Assunto',
      messageLabel: 'Mensagem',
      buttonText: 'Enviar Mensagem',
      successMessage: 'Mensagem enviada com sucesso! Entraremos em contato em breve.',
      showContactInfo: true,
      contactEmail: 'contato@sualoja.com',
      contactPhone: '(11) 99999-9999',
      contactAddress: 'Rua Exemplo, 123 - São Paulo, SP',
      contactHours: 'Seg - Sex: 9h às 18h',
      backgroundColor: '',
      textColor: '',
      buttonBgColor: '',
      buttonTextColor: '',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'simple',
        options: [
          { label: 'Simples', value: 'simple' },
          { label: 'Com Informações', value: 'with-info' },
          { label: 'Lado a Lado', value: 'split' },
        ],
      },
      showName: { type: 'boolean', label: 'Campo Nome', defaultValue: true },
      showPhone: { type: 'boolean', label: 'Campo Telefone', defaultValue: false },
      showSubject: { type: 'boolean', label: 'Campo Assunto', defaultValue: true },
      nameLabel: { type: 'string', label: 'Label Nome' },
      emailLabel: { type: 'string', label: 'Label E-mail' },
      phoneLabel: { type: 'string', label: 'Label Telefone' },
      subjectLabel: { type: 'string', label: 'Label Assunto' },
      messageLabel: { type: 'string', label: 'Label Mensagem' },
      buttonText: { type: 'string', label: 'Texto do Botão' },
      successMessage: { type: 'string', label: 'Mensagem de Sucesso' },
      showContactInfo: { type: 'boolean', label: 'Mostrar Info de Contato', defaultValue: true },
      contactEmail: { type: 'string', label: 'E-mail de Contato' },
      contactPhone: { type: 'string', label: 'Telefone de Contato' },
      contactAddress: { type: 'string', label: 'Endereço' },
      contactHours: { type: 'string', label: 'Horário de Atendimento' },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
      textColor: { type: 'color', label: 'Cor do Texto' },
      buttonBgColor: { type: 'color', label: 'Cor do Botão' },
      buttonTextColor: { type: 'color', label: 'Cor do Texto do Botão' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'Map',
    label: 'Mapa',
    category: 'content',
    icon: 'MapPin',
    defaultProps: {
      title: '',
      subtitle: '',
      address: 'Av. Paulista, 1000 - São Paulo, SP',
      embedUrl: '',
      latitude: '',
      longitude: '',
      zoom: 15,
      height: 'md',
      showAddress: true,
      showDirectionsButton: true,
      directionsButtonText: 'Como Chegar',
      layout: 'full',
      showContactInfo: true,
      contactTitle: 'Nosso Endereço',
      contactAddress: 'Av. Paulista, 1000 - Bela Vista, São Paulo - SP',
      contactPhone: '(11) 99999-9999',
      contactEmail: 'contato@sualoja.com',
      contactHours: 'Seg - Sex: 9h às 18h',
      rounded: true,
      shadow: true,
      backgroundColor: '',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      address: { type: 'string', label: 'Endereço para o Mapa' },
      embedUrl: { type: 'string', label: 'URL do Embed (opcional)', placeholder: 'Cole o URL de incorporação do Google Maps' },
      latitude: { type: 'string', label: 'Latitude (opcional)' },
      longitude: { type: 'string', label: 'Longitude (opcional)' },
      zoom: { type: 'number', label: 'Zoom', defaultValue: 15, min: 1, max: 20 },
      height: {
        type: 'select',
        label: 'Altura',
        defaultValue: 'md',
        options: [
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
          { label: 'Extra Grande', value: 'xl' },
        ],
      },
      showAddress: { type: 'boolean', label: 'Mostrar Endereço', defaultValue: true },
      showDirectionsButton: { type: 'boolean', label: 'Botão "Como Chegar"', defaultValue: true },
      directionsButtonText: { type: 'string', label: 'Texto do Botão' },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'full',
        options: [
          { label: 'Largura Total', value: 'full' },
          { label: 'Com Informações', value: 'with-info' },
          { label: 'Lado a Lado', value: 'side-by-side' },
        ],
      },
      showContactInfo: { type: 'boolean', label: 'Mostrar Info de Contato', defaultValue: true },
      contactTitle: { type: 'string', label: 'Título da Seção' },
      contactAddress: { type: 'string', label: 'Endereço Completo' },
      contactPhone: { type: 'string', label: 'Telefone' },
      contactEmail: { type: 'string', label: 'E-mail' },
      contactHours: { type: 'string', label: 'Horário' },
      rounded: { type: 'boolean', label: 'Bordas Arredondadas', defaultValue: true },
      shadow: { type: 'boolean', label: 'Sombra', defaultValue: true },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'SocialFeed',
    label: 'Feed Social',
    category: 'content',
    icon: 'Instagram',
    defaultProps: {
      title: 'Siga-nos no Instagram',
      subtitle: 'Acompanhe as novidades e compartilhe seus momentos conosco!',
      platform: 'instagram',
      layout: 'grid',
      columns: 6,
      showCaption: false,
      showStats: true,
      maxPosts: 6,
      posts: [],
      showProfile: true,
      profileUsername: '@sualoja',
      profileUrl: 'https://instagram.com/sualoja',
      followButtonText: 'Seguir',
      gap: 'sm',
      rounded: true,
      hoverEffect: true,
      backgroundColor: '',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      platform: {
        type: 'select',
        label: 'Plataforma',
        defaultValue: 'instagram',
        options: [
          { label: 'Instagram', value: 'instagram' },
          { label: 'Facebook', value: 'facebook' },
          { label: 'Twitter', value: 'twitter' },
        ],
      },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'grid',
        options: [
          { label: 'Grade', value: 'grid' },
          { label: 'Carrossel', value: 'carousel' },
          { label: 'Masonry', value: 'masonry' },
        ],
      },
      columns: {
        type: 'select',
        label: 'Colunas',
        defaultValue: '6',
        options: [
          { label: '2 Colunas', value: '2' },
          { label: '3 Colunas', value: '3' },
          { label: '4 Colunas', value: '4' },
          { label: '6 Colunas', value: '6' },
        ],
      },
      showCaption: { type: 'boolean', label: 'Mostrar Legenda', defaultValue: false },
      showStats: { type: 'boolean', label: 'Mostrar Curtidas/Comentários', defaultValue: true },
      maxPosts: { type: 'number', label: 'Máximo de Posts', defaultValue: 6, min: 2, max: 12 },
      showProfile: { type: 'boolean', label: 'Mostrar Perfil', defaultValue: true },
      profileUsername: { type: 'string', label: 'Nome de Usuário' },
      profileUrl: { type: 'string', label: 'URL do Perfil' },
      followButtonText: { type: 'string', label: 'Texto do Botão Seguir' },
      gap: {
        type: 'select',
        label: 'Espaçamento',
        defaultValue: 'sm',
        options: [
          { label: 'Pequeno', value: 'sm' },
          { label: 'Médio', value: 'md' },
          { label: 'Grande', value: 'lg' },
        ],
      },
      rounded: { type: 'boolean', label: 'Bordas Arredondadas', defaultValue: true },
      hoverEffect: { type: 'boolean', label: 'Efeito Hover', defaultValue: true },
      backgroundColor: { type: 'color', label: 'Cor de Fundo' },
    },
    canHaveChildren: false,
    isRemovable: true,
  },
  {
    type: 'PersonalizedProducts',
    label: 'Produtos Personalizados',
    category: 'content',
    icon: 'Sparkles',
    defaultProps: {
      title: 'Recomendados para Você',
      subtitle: 'Produtos selecionados com base em suas preferências',
      layout: 'grid',
      columns: 4,
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'grid',
        options: [
          { label: 'Grade', value: 'grid' },
          { label: 'Carrossel', value: 'carousel' },
        ],
      },
      columns: {
        type: 'select',
        label: 'Colunas',
        defaultValue: '4',
        options: [
          { label: '2 Colunas', value: '2' },
          { label: '3 Colunas', value: '3' },
          { label: '4 Colunas', value: '4' },
        ],
      },
    },
    canHaveChildren: false,
  },
  {
    type: 'LivePurchases',
    label: 'Comprando Agora',
    category: 'content',
    icon: 'ShoppingCart',
    defaultProps: {
      title: 'Comprando Agora',
      layout: 'cards',
      showStats: true,
      purchasesToday: 127,
      viewersNow: 43,
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'cards',
        options: [
          { label: 'Cards', value: 'cards' },
          { label: 'Ticker', value: 'ticker' },
          { label: 'Popup', value: 'popup' },
        ],
      },
      showStats: { type: 'boolean', label: 'Mostrar Estatísticas', defaultValue: true },
    },
    canHaveChildren: false,
  },
  {
    type: 'PricingTable',
    label: 'Tabela de Preços',
    category: 'content',
    icon: 'CreditCard',
    defaultProps: {
      title: 'Escolha o Plano Ideal',
      subtitle: 'Comece gratuitamente e escale conforme cresce',
      layout: 'cards',
      showAnnualToggle: true,
      annualDiscount: 20,
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'cards',
        options: [
          { label: 'Cards', value: 'cards' },
          { label: 'Tabela', value: 'table' },
        ],
      },
      showAnnualToggle: { type: 'boolean', label: 'Toggle Mensal/Anual', defaultValue: true },
      annualDiscount: { type: 'number', label: 'Desconto Anual (%)', defaultValue: 20, min: 0, max: 50 },
    },
    canHaveChildren: false,
  },
  {
    type: 'PopupModal',
    label: 'Popup/Modal',
    category: 'content',
    icon: 'Bell',
    defaultProps: {
      title: 'Receba Ofertas Exclusivas!',
      subtitle: 'Cadastre-se e ganhe 10% de desconto na primeira compra',
      type: 'newsletter',
      layout: 'centered',
      showEmailInput: true,
      buttonText: 'Quero meu desconto!',
      discountCode: 'BEMVINDO10',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título' },
      subtitle: { type: 'string', label: 'Subtítulo' },
      type: {
        type: 'select',
        label: 'Tipo',
        defaultValue: 'newsletter',
        options: [
          { label: 'Newsletter', value: 'newsletter' },
          { label: 'Promoção', value: 'promotion' },
          { label: 'Anúncio', value: 'announcement' },
        ],
      },
      layout: {
        type: 'select',
        label: 'Layout',
        defaultValue: 'centered',
        options: [
          { label: 'Centralizado', value: 'centered' },
          { label: 'Com Imagem', value: 'side-image' },
          { label: 'Canto', value: 'corner' },
        ],
      },
      showEmailInput: { type: 'boolean', label: 'Mostrar Campo Email', defaultValue: true },
      buttonText: { type: 'string', label: 'Texto do Botão' },
      discountCode: { type: 'string', label: 'Código de Desconto' },
    },
    canHaveChildren: false,
  },

  // ========== OFFER SLOT BLOCKS ==========
  {
    type: 'CompreJuntoSlot',
    label: 'Compre Junto',
    category: 'ecommerce',
    icon: 'ShoppingBag',
    defaultProps: {
      title: 'Compre Junto',
      subtitle: 'Aproveite e leve também',
      maxItems: 3,
      variant: 'normal',
      showWhenEmpty: true,
      ctaLabel: 'Configurar ofertas',
      ctaHref: '/offers',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título', defaultValue: 'Compre Junto' },
      subtitle: { type: 'string', label: 'Subtítulo (opcional)', defaultValue: '' },
      maxItems: { type: 'number', label: 'Máximo de Itens', defaultValue: 3, min: 1, max: 6 },
      variant: {
        type: 'select',
        label: 'Variante',
        defaultValue: 'normal',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Compacto', value: 'compact' },
        ],
      },
      showWhenEmpty: { type: 'boolean', label: 'Mostrar quando vazio', defaultValue: true },
      ctaLabel: { type: 'string', label: 'Texto do CTA', defaultValue: 'Configurar ofertas' },
      ctaHref: { type: 'string', label: 'Link do CTA', defaultValue: '/offers' },
    },
    canHaveChildren: false,
  },
  {
    type: 'CrossSellSlot',
    label: 'Sugestões no Carrinho',
    category: 'ecommerce',
    icon: 'Gift',
    defaultProps: {
      title: 'Você também pode gostar',
      subtitle: '',
      maxItems: 4,
      variant: 'normal',
      showWhenEmpty: true,
      ctaLabel: 'Configurar ofertas',
      ctaHref: '/offers',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título', defaultValue: 'Você também pode gostar' },
      subtitle: { type: 'string', label: 'Subtítulo (opcional)', defaultValue: '' },
      maxItems: { type: 'number', label: 'Máximo de Itens', defaultValue: 4, min: 1, max: 8 },
      variant: {
        type: 'select',
        label: 'Variante',
        defaultValue: 'normal',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Compacto', value: 'compact' },
        ],
      },
      showWhenEmpty: { type: 'boolean', label: 'Mostrar quando vazio', defaultValue: true },
      ctaLabel: { type: 'string', label: 'Texto do CTA', defaultValue: 'Configurar ofertas' },
      ctaHref: { type: 'string', label: 'Link do CTA', defaultValue: '/offers' },
    },
    canHaveChildren: false,
  },
  // NOTE: OrderBumpSlot was REMOVED - duplicated logic with CheckoutContent's internal OrderBumpSection
  // Order Bump is now handled ONLY internally by Checkout block, controlled by showOrderBump toggle
  {
    type: 'UpsellSlot',
    label: 'Oferta Pós-Compra',
    category: 'ecommerce',
    icon: 'TrendingUp',
    defaultProps: {
      title: 'Oferta Especial',
      subtitle: 'Aproveite esta oferta exclusiva!',
      maxItems: 3,
      variant: 'normal',
      showWhenEmpty: true,
      ctaLabel: 'Configurar ofertas',
      ctaHref: '/offers',
    },
    propsSchema: {
      title: { type: 'string', label: 'Título', defaultValue: 'Oferta Especial' },
      subtitle: { type: 'string', label: 'Subtítulo (opcional)', defaultValue: 'Aproveite esta oferta exclusiva!' },
      maxItems: { type: 'number', label: 'Máximo de Itens', defaultValue: 3, min: 1, max: 6 },
      variant: {
        type: 'select',
        label: 'Variante',
        defaultValue: 'normal',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Compacto', value: 'compact' },
        ],
      },
      showWhenEmpty: { type: 'boolean', label: 'Mostrar quando vazio', defaultValue: true },
      ctaLabel: { type: 'string', label: 'Texto do CTA', defaultValue: 'Configurar ofertas' },
      ctaHref: { type: 'string', label: 'Link do CTA', defaultValue: '/offers' },
    },
    canHaveChildren: false,
  },
];

// Registry class
class BlockRegistry {
  private blocks: Map<string, BlockDefinition> = new Map();

  constructor() {
    blockDefinitions.forEach(block => {
      this.blocks.set(block.type, block);
    });
  }

  get(type: string): BlockDefinition | undefined {
    return this.blocks.get(type);
  }

  getAll(): BlockDefinition[] {
    return Array.from(this.blocks.values());
  }

  getByCategory(category: BlockCategory): BlockDefinition[] {
    return this.getAll().filter(block => block.category === category);
  }

  getCategorizedBlocks(): Record<BlockCategory, BlockDefinition[]> {
    return {
      layout: this.getByCategory('layout'),
      'header-footer': this.getByCategory('header-footer'),
      content: this.getByCategory('content'),
      media: this.getByCategory('media'),
      ecommerce: this.getByCategory('ecommerce'),
      utilities: this.getByCategory('utilities'),
    };
  }

  exists(type: string): boolean {
    return this.blocks.has(type);
  }

  createDefaultNode(type: string): BlockNode | null {
    const definition = this.get(type);
    if (!definition) return null;

    return {
      id: `${type.toLowerCase()}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      type,
      props: { ...definition.defaultProps },
      children: definition.canHaveChildren ? [] : undefined,
    };
  }
}

// Singleton instance
export const blockRegistry = new BlockRegistry();

// Category labels
export const categoryLabels: Record<BlockCategory, string> = {
  layout: 'Layout',
  'header-footer': 'Cabeçalho / Rodapé',
  content: 'Conteúdo',
  media: 'Mídia',
  ecommerce: 'E-commerce',
  utilities: 'Utilitários',
};
