export interface QuestionnaireQuestion {
  number: number;
  text: string;
}

export interface QuestionnaireBlock {
  key: string;
  title: string;
  questions: QuestionnaireQuestion[];
}

export const questionnaireBlocks: QuestionnaireBlock[] = [
  {
    key: "bloco_1",
    title: "Bloco 1 – Core vendável e prioridade",
    questions: [
      { number: 1, text: "Quais módulos formam o core vendável do Comando Central no primeiro lançamento?" },
      { number: 2, text: "Quais fluxos são Críticos, Altos, Médios e Baixos?" },
      { number: 3, text: "Se tivesse que congelar tudo e lançar só o essencial, o que obrigatoriamente teria que estar 100% fechado?" },
      { number: 4, text: "O que pode ficar com feature flag, beta interno ou incompleto sem impedir venda?" },
      { number: 5, text: "Entre estes 3 grupos, qual é a prioridade máxima agora: funil de venda da loja, operação do lojista ou operação do SaaS/plataforma?" },
      { number: 6, text: "Em dúvida entre segurança e velocidade, qual lado vence por padrão?" },
    ],
  },
  {
    key: "bloco_2",
    title: "Bloco 2 – Pedido, checkout e pagamento",
    questions: [
      { number: 7, text: "Em qual momento o checkout vira pedido real?" },
      { number: 8, text: "Em qual momento o checkout passa a ser considerado abandono real?" },
      { number: 9, text: "Pedido criado sem pagamento aprovado deve existir? Se sim, com qual status operacional?" },
      { number: 10, text: "Pagamento aprovado sem pedido válido deve gerar correção automática, alerta ou bloqueio?" },
      { number: 11, text: "Em divergência temporária entre gateway e sistema, quem é a fonte de verdade provisória?" },
      { number: 12, text: "Em cobrança duplicada, qual deve ser o comportamento padrão?" },
      { number: 13, text: "Se webhook falhar, o sistema deve ter fallback de reconciliação automática?" },
      { number: 14, text: "Em divergência entre checkout, pagamento, pedido e tracking, qual deles deve ser reconciliado primeiro?" },
    ],
  },
  {
    key: "bloco_3",
    title: "Bloco 3 – Estoque, cancelamento e reembolso",
    questions: [
      { number: 15, text: "Em qual momento o estoque deve ser decrementado?" },
      { number: 16, text: "Se o pagamento falhar, expirar ou for recusado, o estoque deve voltar? Como?" },
      { number: 17, text: "Qual é o fluxo canônico de cancelamento de pedido?" },
      { number: 18, text: "Pedido pago cancelado deve gerar reembolso automático, manual ou depender do caso?" },
      { number: 19, text: "No cancelamento, o estoque deve voltar automaticamente?" },
      { number: 20, text: "Pedido manual criado pelo admin segue o mesmo fluxo de status do pedido normal ou tem fluxo próprio?" },
      { number: 21, text: "Pedido manual pode existir sem vínculo com gateway? Se sim, como deve ser tratado no core?" },
      { number: 22, text: "Como evitar que pedido manual caia em filtros errados, como ghost order?" },
    ],
  },
  {
    key: "bloco_4",
    title: "Bloco 4 – Clientes, leads, subscribers, tags e listas",
    questions: [
      { number: 23, text: "Você confirma a separação oficial entre lead, subscriber e customer?" },
      { number: 24, text: "Em quais eventos um lead nasce oficialmente?" },
      { number: 25, text: "Em quais eventos um subscriber nasce oficialmente?" },
      { number: 26, text: "Em quais eventos um customer nasce oficialmente?" },
      { number: 27, text: "Quando exatamente a tag sistêmica Cliente deve ser aplicada?" },
      { number: 28, text: "Essa tag pode ser removida? Se sim, em quais cenários?" },
      { number: 29, text: "Em caso de divergência entre customer, subscriber, tag e lista, quem vence?" },
      { number: 30, text: "A sincronização entre tag e lista deve ser em tempo real, periódica ou híbrida?" },
      { number: 31, text: "Se houver divergência entre tag e lista, o sistema deve corrigir automaticamente, sinalizar ou aguardar decisão manual?" },
    ],
  },
  {
    key: "bloco_5",
    title: "Bloco 5 – Catálogo, loja pública, domínio e builder",
    questions: [
      { number: 32, text: "Produto inativo deve sumir totalmente da loja ou continuar acessível por URL direta?" },
      { number: 33, text: "Categoria vazia deve continuar pública ou ser ocultada?" },
      { number: 34, text: "A ordenação do catálogo público deve ser manual, automática ou híbrida?" },
      { number: 35, text: "Quando o tenant configura domínio próprio, qual é o fluxo canônico esperado?" },
      { number: 36, text: "O domínio próprio impacta quais áreas: loja pública, checkout, emails transacionais, tracking ou todas?" },
      { number: 37, text: "Em problema de domínio/SSL, o sistema deve bloquear publicação, usar domínio padrão como fallback ou seguir de outra forma?" },
      { number: 38, text: "Mudança em bloco do Builder deve exigir validação pública da página correspondente?" },
      { number: 39, text: "Quais blocos/áreas do Builder são considerados sensíveis?" },
      { number: 40, text: "Componente compartilhado entre Admin e Storefront pode ser alterado sem validar os dois contextos?" },
    ],
  },
  {
    key: "bloco_6",
    title: "Bloco 6 – Eventos, webhooks, trigger, cron e retry",
    questions: [
      { number: 41, text: "Quais fluxos devem ser obrigatoriamente trigger principal + cron fallback?" },
      { number: 42, text: "Quais fluxos podem ser apenas por cron sem problema?" },
      { number: 43, text: "Quando um webhook falhar por timeout/500, qual deve ser a política de retry?" },
      { number: 44, text: "Após quantas falhas um evento deve entrar oficialmente como erro recorrente?" },
      { number: 45, text: "Você quer fila de reprocessamento manual para eventos críticos?" },
      { number: 46, text: "Quando a reconciliação automática deve corrigir sozinha e quando deve parar para te avisar?" },
      { number: 47, text: "Quando uma retentativa de pagamento acontece, ela deve reutilizar o mesmo pedido ou criar um novo vinculado ao anterior?" },
      { number: 48, text: "Quantas retentativas de pagamento são permitidas por checkout/pedido?" },
      { number: 49, text: "Por quanto tempo a retentativa deve ficar disponível após recusa/falha?" },
      { number: 50, text: "Em retry aprovado, o sistema deve atualizar o pedido original, manter histórico vinculado ou criar novo pedido comercial?" },
    ],
  },
  {
    key: "bloco_7",
    title: "Bloco 7 – Integrações externas",
    questions: [
      { number: 51, text: "Quais integrações externas são críticas para lançamento?" },
      { number: 52, text: "Se uma integração externa falhar, o sistema deve degradar com segurança, bloquear o fluxo ou seguir com pendência?" },
      { number: 53, text: "Se um marketplace ou provedor enviar dado inconsistente com o core, quem vence?" },
      { number: 54, text: "Você quer regra formal de que integração externa nunca altera o core diretamente sem passar pelo contrato interno?" },
      { number: 55, text: "O que deve ser considerado erro crítico de integração e o que deve ser tolerável?" },
      { number: 56, text: "Quais integrações precisam obrigatoriamente de fallback manual?" },
    ],
  },
  {
    key: "bloco_8",
    title: "Bloco 8 – Planos, limites e feature gating",
    questions: [
      { number: 57, text: "Quais features devem estar claramente gated por plano?" },
      { number: 58, text: "Quais features devem ficar liberadas para todos?" },
      { number: 59, text: "Quais features devem ficar só no tenant admin até validação?" },
      { number: 60, text: "Quando uma feature estiver incompleta, ela deve ser escondida, mostrada como indisponível ou liberada parcialmente?" },
      { number: 61, text: "Qual deve ser a fonte de verdade do gating: plan_module_access, FEATURE_CONFIG ou um modelo híbrido?" },
      { number: 62, text: "Quando um módulo estiver bloqueado por plano, ele deve sumir do menu, aparecer com cadeado, aparecer com CTA de upgrade ou depender do módulo?" },
      { number: 63, text: "O bloqueio por plano deve valer para módulo inteiro, partes do módulo, ações específicas ou tudo isso?" },
    ],
  },
  {
    key: "bloco_9",
    title: "Bloco 9 – Notificações, WhatsApp e emails transacionais",
    questions: [
      { number: 64, text: "Quais notificações ao lojista são obrigatórias no lançamento?" },
      { number: 65, text: "Quais notificações ao cliente são obrigatórias no lançamento?" },
      { number: 66, text: "O WhatsApp entra em quais fluxos canônicos?" },
      { number: 67, text: "Quais emails transacionais são obrigatórios no lançamento?" },
      { number: 68, text: "O envio de emails transacionais deve usar domínio padrão da plataforma, domínio do tenant quando disponível ou modelo híbrido?" },
      { number: 69, text: "Se o domínio do tenant não estiver pronto, qual deve ser o fallback?" },
      { number: 70, text: "Templates de emails transacionais devem ser fixos ou editáveis pelo lojista?" },
    ],
  },
  {
    key: "bloco_10",
    title: "Bloco 10 – Segurança, tenants e ações sensíveis",
    questions: [
      { number: 71, text: "Quais ações devem ser exclusivas do owner?" },
      { number: 72, text: "Quais ações o admin do tenant pode executar sem risco?" },
      { number: 73, text: "Quais ações o operator nunca deve executar?" },
      { number: 74, text: "Você quer dupla confirmação para exclusões, resets e reparos sensíveis?" },
      { number: 75, text: "Em incidente de tenant/risco de vazamento, o sistema deve bloquear automaticamente, alertar, ou registrar e seguir?" },
      { number: 76, text: "Quais dados nunca podem sofrer reparo em massa sem sua autorização?" },
    ],
  },
  {
    key: "bloco_11",
    title: "Bloco 11 – Erros recorrentes, fechamento e docs",
    questions: [
      { number: 77, text: "Quais foram os erros/regressões mais graves já ocorridos?" },
      { number: 78, text: "Quais erros costumam voltar mais?" },
      { number: 79, text: "O que faz um erro entrar oficialmente na lista de erros recorrentes?" },
      { number: 80, text: "O que define bug resolvido de verdade para você?" },
      { number: 81, text: "Mudança visual simples deve usar checklist completo, checklist reduzido ou decisão caso a caso?" },
      { number: 82, text: "Quando uma implementação impactar docs, você quer atualização automática se já autorizada, proposta de atualização para confirmação, ou depende do tipo de doc?" },
      { number: 83, text: "Quais docs podem ser atualizados automaticamente sem nova confirmação?" },
      { number: 84, text: "O Doc de Regras do Sistema só pode ser alterado com sua confirmação explícita?" },
    ],
  },
  {
    key: "bloco_12",
    title: "Bloco 12 – Dashboard / Central de Comando",
    questions: [
      { number: 85, text: "Quais widgets e KPIs são obrigatórios na tela inicial do lojista no lançamento?" },
      { number: 86, text: "O dashboard deve priorizar dados em tempo real, dados com cache, ou modelo híbrido?" },
      { number: 87, text: "Quais números precisam aparecer obrigatoriamente na primeira tela?" },
      { number: 88, text: "O dashboard deve ter visão geral, por canal, por período, ou tudo isso?" },
      { number: 89, text: "O dashboard é apenas leitura ou pode ter ações rápidas operacionais?" },
    ],
  },
  {
    key: "bloco_13",
    title: "Bloco 13 – Área do Cliente",
    questions: [
      { number: 90, text: "O que o cliente final pode fazer na Área do Cliente no lançamento?" },
      { number: 91, text: "O cliente pode ver pedidos, acompanhar status, editar endereço, cancelar pedido, solicitar troca/devolução ou baixar comprovantes?" },
      { number: 92, text: "O que é obrigatório e o que pode ficar para depois?" },
      { number: 93, text: "A Área do Cliente usa o mesmo login da loja ou um fluxo separado?" },
      { number: 94, text: "Há alguma ação que o cliente nunca deve poder fazer sozinho?" },
    ],
  },
  {
    key: "bloco_14",
    title: "Bloco 14 – Avaliações",
    questions: [
      { number: 95, text: "Avaliação pode ser publicada automaticamente ou precisa de moderação?" },
      { number: 96, text: "Só cliente que comprou pode avaliar?" },
      { number: 97, text: "Avaliação negativa publica direto ou entra em revisão?" },
      { number: 98, text: "Cliente pode editar ou excluir avaliação depois?" },
      { number: 99, text: "Avaliações importadas seguem o mesmo fluxo das avaliações nativas?" },
      { number: 100, text: "Avaliação negativa deve disparar alguma ação automática, alerta ou tag?" },
    ],
  },
  {
    key: "bloco_15",
    title: "Bloco 15 – Descontos / Cupons",
    questions: [
      { number: 101, text: "Cupons podem ser acumulados com outros descontos?" },
      { number: 102, text: "Cupom pode coexistir com bump, upsell e oferta?" },
      { number: 103, text: "Qual é a regra de prioridade quando houver conflito entre cupom, desconto automático, oferta, bump e upsell?" },
      { number: 104, text: "Existe limite de uso por cliente?" },
      { number: 105, text: "Cupom expirado deve sumir, continuar visível com erro, ou ficar oculto no checkout?" },
      { number: 106, text: "Desconto aplica em quais bases: subtotal, produto, frete ou pedido inteiro?" },
    ],
  },
  {
    key: "bloco_16",
    title: "Bloco 16 – Aumentar Ticket (Bump / Upsell / Ofertas)",
    questions: [
      { number: 107, text: "Bump e upsell podem coexistir no mesmo fluxo?" },
      { number: 108, text: "Qual é a prioridade de exibição quando há múltiplas ofertas ativas?" },
      { number: 109, text: "Oferta recusada pode reaparecer?" },
      { number: 110, text: "Oferta pode coexistir com cupom?" },
      { number: 111, text: "Em caso de conflito entre aumento de ticket e desconto, quem vence?" },
      { number: 112, text: "Em que momento cada tipo deve aparecer: página de produto, carrinho, checkout ou pós-compra?" },
    ],
  },
  {
    key: "bloco_17",
    title: "Bloco 17 – Blog",
    questions: [
      { number: 113, text: "Publicação de post é imediata, rascunho, agendada ou híbrida?" },
      { number: 114, text: "Blog precisa ter SEO próprio?" },
      { number: 115, text: "Blog impacta sitemap, campanhas, email marketing ou páginas de loja?" },
      { number: 116, text: "Quem pode publicar post?" },
      { number: 117, text: "O blog usa o mesmo builder da loja ou fluxo próprio?" },
    ],
  },
  {
    key: "bloco_18",
    title: "Bloco 18 – Quizzes",
    questions: [
      { number: 118, text: "Qual é o papel do quiz no funil?" },
      { number: 119, text: "Quiz gera lead, subscriber, apenas dado analítico ou recomendação de produto?" },
      { number: 120, text: "Resultado do quiz pode aplicar tag, gerar desconto, direcionar oferta ou criar automação?" },
      { number: 121, text: "Quiz é módulo transacional, marketing ou híbrido?" },
    ],
  },
  {
    key: "bloco_19",
    title: "Bloco 19 – Atribuição de Venda",
    questions: [
      { number: 122, text: "Qual é o modelo oficial de atribuição?" },
      { number: 123, text: "Em conflito entre UTM, pixel e tracking interno, quem vence?" },
      { number: 124, text: "A atribuição serve só para relatório ou também afeta automações e comissão?" },
      { number: 125, text: "Qual é a janela de atribuição oficial?" },
      { number: 126, text: "A atribuição será por pedido, por cliente, por sessão ou híbrida?" },
    ],
  },
  {
    key: "bloco_20",
    title: "Bloco 20 – Agentes de IA e Orquestração",
    questions: [
      { number: 127, text: "Quais agentes existem oficialmente no sistema hoje?" },
      { number: 128, text: "Qual é a função de cada um?" },
      { number: 129, text: "Quais agentes podem apenas consultar, sugerir, executar ação ou executar ação crítica?" },
      { number: 130, text: "Como os agentes conversam entre si?" },
      { number: 131, text: "Existe um agente orquestrador ou cada agente atua isoladamente?" },
      { number: 132, text: "Em conflito entre agentes, quem vence?" },
      { number: 133, text: "Qual agente manda em qual domínio?" },
      { number: 134, text: "Quais ações exigem confirmação humana mesmo quando sugeridas por agente?" },
      { number: 135, text: "Agentes podem alterar pedidos, clientes, produtos, campanhas, configurações, ou nenhum sem confirmação?" },
      { number: 136, text: "Toda ação de agente deve gerar auditoria?" },
      { number: 137, text: "O agente de tráfego cria campanhas sozinho, só sugere ou executa com trava?" },
      { number: 138, text: "O Assistente IA geral pode atuar em todos os módulos ou só orientar?" },
      { number: 139, text: "O Auxiliar de Comando tem papel operacional, analítico ou ambos?" },
      { number: 140, text: "Como funciona consumo, custo e limite de uso dos agentes?" },
    ],
  },
  {
    key: "bloco_21",
    title: "Bloco 21 – Central de Conteúdo / Criativos",
    questions: [
      { number: 141, text: "Qual é o fluxo canônico entre calendário, criativos, campanhas e blog?" },
      { number: 142, text: "O estúdio de criativos gera imagens IA, vídeos IA, templates ou tudo isso?" },
      { number: 143, text: "Conteúdo gerado pode ser publicado direto ou só salvo como rascunho?" },
      { number: 144, text: "O calendário integra com quais canais?" },
      { number: 145, text: "Quem pode aprovar ou publicar conteúdo?" },
      { number: 146, text: "Conteúdo criado por IA precisa sempre de revisão humana?" },
    ],
  },
  {
    key: "bloco_22",
    title: "Bloco 22 – Afiliados",
    questions: [
      { number: 147, text: "Qual é o modelo de comissão?" },
      { number: 148, text: "Comissão nasce em qual evento: pedido pago, pedido entregue ou outro?" },
      { number: 149, text: "Payout é automático ou manual?" },
      { number: 150, text: "Afiliado pode ver quais dados?" },
      { number: 151, text: "A atribuição do afiliado é por link, cupom ou ambos?" },
      { number: 152, text: "Qual é a janela de atribuição do afiliado?" },
    ],
  },
  {
    key: "bloco_23",
    title: "Bloco 23 – Influencers",
    questions: [
      { number: 153, text: "Influencer e afiliado compartilham estrutura ou são fluxos separados?" },
      { number: 154, text: "Qual é o ciclo de vida do influencer?" },
      { number: 155, text: "Influencer tem painel próprio ou é gestão interna?" },
      { number: 156, text: "Tracking do influencer é por link, cupom, campanha ou híbrido?" },
      { number: 157, text: "Como se mede resultado do influencer?" },
    ],
  },
  {
    key: "bloco_24",
    title: "Bloco 24 – Marketplaces",
    questions: [
      { number: 158, text: "Pedidos de marketplace seguem exatamente o mesmo fluxo canônico de pedido ou tem exceções?" },
      { number: 159, text: "Estoque é compartilhado entre loja própria e marketplaces?" },
      { number: 160, text: "Preço pode variar por canal?" },
      { number: 161, text: "Quais marketplaces são prioridade de lançamento?" },
      { number: 162, text: "TikTok Shop e Olist seguem a mesma regra de Mercado Livre/Shopee ou tem exceções?" },
      { number: 163, text: "Se marketplace mandar dado inconsistente, o core vence sempre?" },
      { number: 164, text: "Marketplaces podem criar ou alterar status de pedido ou só alimentar o fluxo oficial?" },
    ],
  },
  {
    key: "bloco_25",
    title: "Bloco 25 – Meu Drive / Arquivos",
    questions: [
      { number: 165, text: "Existe limite de armazenamento por plano?" },
      { number: 166, text: "Quais tipos de arquivo são aceitos?" },
      { number: 167, text: "Os arquivos do drive são compartilhados entre quais módulos?" },
      { number: 168, text: "Há regra de organização por pastas obrigatória?" },
      { number: 169, text: "Arquivos excluídos do drive podem quebrar outros módulos? Como tratar isso?" },
    ],
  },
  {
    key: "bloco_26",
    title: "Bloco 26 – Relatórios",
    questions: [
      { number: 170, text: "Quais relatórios são obrigatórios no lançamento?" },
      { number: 171, text: "Qual é a fonte de verdade dos números dos relatórios?" },
      { number: 172, text: "Relatórios precisam ter exportação?" },
      { number: 173, text: "Relatórios são apenas analíticos ou também operacionais?" },
      { number: 174, text: "Qual a diferença entre dashboard e relatórios no produto?" },
    ],
  },
  {
    key: "bloco_27",
    title: "Bloco 27 – Plataforma Admin / Billing / Health / Tenants",
    questions: [
      { number: 175, text: "Quais métricas o Health Monitor precisa acompanhar?" },
      { number: 176, text: "O admin da plataforma pode fazer quais ações dentro de tenants?" },
      { number: 177, text: "Qual é o fluxo de billing/assinatura da plataforma?" },
      { number: 178, text: "Existe trial? Existe carência?" },
      { number: 179, text: "O que acontece quando o tenant não paga?" },
      { number: 180, text: "Após quanto tempo bloquear?" },
      { number: 181, text: "O bloqueio por inadimplência afeta admin, storefront ou ambos?" },
      { number: 182, text: "Avisos e tutoriais são por módulo, por plano, globais ou híbridos?" },
    ],
  },
  {
    key: "bloco_28",
    title: "Bloco 28 – Configurações do Sistema",
    questions: [
      { number: 183, text: "Quais configurações mínimas o tenant precisa completar para operar?" },
      { number: 184, text: "Configuração incompleta deve bloquear, alertar ou permitir seguir com risco?" },
      { number: 185, text: "Quais configurações são obrigatórias antes de publicar a loja?" },
      { number: 186, text: "Quais configurações são obrigatórias antes de vender?" },
    ],
  },
  {
    key: "bloco_29",
    title: "Bloco 29 – Landing Pages",
    questions: [
      { number: 187, text: "Landing pages usam o mesmo builder da loja ou um builder próprio?" },
      { number: 188, text: "Landing page pode ter checkout embutido?" },
      { number: 189, text: "Como landing pages se conectam com campanhas, tracking e atribuição?" },
      { number: 190, text: "Landing page é tratada como parte da loja ou como fluxo separado?" },
    ],
  },
  {
    key: "bloco_30",
    title: "Bloco 30 – Suporte ao Lojista",
    questions: [
      { number: 191, text: "O suporte é chat, ticket ou ambos?" },
      { number: 192, text: "Esse suporte é da plataforma para o lojista, do lojista para o cliente final, ou ambos?" },
      { number: 193, text: "O que é obrigatório no lançamento?" },
      { number: 194, text: "O suporte se integra com WhatsApp, email e CRM?" },
    ],
  },
  {
    key: "bloco_u",
    title: "Bloco U – Builder / Editor Visual",
    questions: [
      { number: 195, text: "Quais páginas do Builder são obrigatórias no lançamento (Home, Produto, Categoria, Obrigado, outras)?" },
      { number: 196, text: "Quais blocos são obrigatórios por tipo de página?" },
      { number: 197, text: "O que é estrutura fixa e o que é estrutura livre dentro do Builder?" },
      { number: 198, text: "Header, Footer e Checkout são fixos, parcialmente editáveis ou livres?" },
      { number: 199, text: "Quais regras de publicação devem existir: rascunho, preview, publicar e rollback?" },
      { number: 200, text: "Quem pode editar o que dentro do Builder?" },
      { number: 201, text: "Como validar a paridade entre editor e loja pública?" },
      { number: 202, text: "Como tratar bloco quebrado, inválido ou incompatível?" },
      { number: 203, text: "Blocos gerados por IA podem publicar direto ou só gerar rascunho?" },
      { number: 204, text: "Mudanças em Header, Footer e Checkout exigem trava extra?" },
      { number: 205, text: "Mídia usada nos blocos segue exatamente as mesmas regras do Meu Drive?" },
    ],
  },
  {
    key: "bloco_v",
    title: "Bloco V – Pacotes IA",
    questions: [
      { number: 206, text: "Como funciona o modelo de créditos e consumo de IA?" },
      { number: 207, text: "Quais ações consomem créditos de IA?" },
      { number: 208, text: "O que acontece quando os créditos acabam: bloqueia, degrada ou alerta?" },
      { number: 209, text: "O lojista pode comprar pacotes avulsos?" },
      { number: 210, text: "Existe pacote de IA incluso no plano?" },
    ],
  },
  {
    key: "bloco_w",
    title: "Bloco W – Onboarding / Getting Started",
    questions: [
      { number: 211, text: "Qual é o fluxo de onboarding obrigatório para novos tenants?" },
      { number: 212, text: "O lojista pode pular etapas do onboarding?" },
      { number: 213, text: "Quais etapas bloqueiam operação se não forem completadas?" },
      { number: 214, text: "O onboarding reaparece se configurações ficarem incompletas?" },
    ],
  },
  {
    key: "bloco_x",
    title: "Bloco X – Domínios e Conta do Lojista",
    questions: [
      { number: 215, text: "O lojista pode ter múltiplos domínios ativos?" },
      { number: 216, text: "Quais dados da conta do lojista (CNPJ, endereço, dados fiscais, outros) são obrigatórios para quais funcionalidades?" },
      { number: 217, text: "O billing do tenant é separado do billing da plataforma?" },
    ],
  },
  {
    key: "bloco_y",
    title: "Bloco Y – Integrações (escopo detalhado)",
    questions: [
      { number: 218, text: "Quais categorias de integração existem oficialmente no sistema?" },
      { number: 219, text: "Quais integrações são nativas e quais são configuráveis pelo lojista?" },
      { number: 220, text: "O lojista pode adicionar integrações próprias ou webhooks customizados?" },
      { number: 221, text: "Desconectar uma integração impacta dados históricos? Se sim, como?" },
    ],
  },
  {
    key: "bloco_z",
    title: "Bloco Z – ERP: Fiscal, Financeiro e Compras",
    questions: [
      { number: 222, text: "Qual é o regime fiscal padrão esperado por tenant e ele pode variar por operação?" },
      { number: 223, text: "A emissão de nota fiscal deve ser automática, manual ou híbrida?" },
      { number: 224, text: "Em qual momento do fluxo do pedido a nota fiscal deve ser gerada?" },
      { number: 225, text: "Se houver divergência entre pedido e módulo fiscal, quem vence e como reconciliar?" },
      { number: 226, text: "Qual é a fonte de verdade da conciliação financeira: sistema interno, gateway, banco ou modelo híbrido?" },
      { number: 227, text: "O financeiro deve cobrir quais áreas no lançamento: contas a pagar, contas a receber, conciliação, caixa, DRE ou outras?" },
      { number: 228, text: "Qual é o fluxo canônico de compras e reposição de estoque?" },
      { number: 229, text: "Entrada de compra deve impactar estoque automaticamente?" },
      { number: 230, text: "Cancelamento, reembolso e chargeback devem refletir automaticamente no financeiro e no fiscal?" },
    ],
  },
  {
    key: "bloco_aa",
    title: "Bloco AA – Importação de Dados",
    questions: [
      { number: 231, text: "Quais formatos de importação são aceitos oficialmente no lançamento?" },
      { number: 232, text: "Importação deve ter preview obrigatório antes de executar?" },
      { number: 233, text: "Quais validações pré-importação são obrigatórias?" },
      { number: 234, text: "Em conflito com dados existentes, a importação deve sobrescrever, mesclar, bloquear ou depender do módulo?" },
      { number: 235, text: "Importação pode criar registros incompletos no core ou deve rejeitar sempre?" },
      { number: 236, text: "Importação parcial com erros deve abortar tudo ou importar apenas os válidos com relatório?" },
      { number: 237, text: "Deve existir rollback ou reversão de importação?" },
      { number: 238, text: "Importação deve ter limites por plano, volume ou tipo de dado?" },
    ],
  },
  {
    key: "bloco_ab",
    title: "Bloco AB – Menus da Loja",
    questions: [
      { number: 239, text: "Os menus da loja são livres, semi-estruturados ou baseados em estrutura fixa?" },
      { number: 240, text: "Menus devem sincronizar automaticamente com categorias e páginas institucionais?" },
      { number: 241, text: "Desktop e mobile compartilham o mesmo menu ou podem ter estruturas diferentes?" },
      { number: 242, text: "Existe limite de níveis de navegação no menu?" },
      { number: 243, text: "Menus podem conter links externos, páginas customizadas, categorias, produtos ou tudo isso?" },
      { number: 244, text: "Mudanças de menu devem exigir validação pública antes de publicar?" },
    ],
  },
  {
    key: "bloco_ac",
    title: "Bloco AC – Logística / Shipping",
    questions: [
      { number: 245, text: "Quais transportadoras são suportadas no lançamento?" },
      { number: 246, text: "O cálculo de frete no lançamento deve usar tabela fixa, API de transportadora ou modelo híbrido?" },
      { number: 247, text: "Qual é a fonte de verdade do rastreamento: sistema interno, transportadora ou modelo híbrido?" },
      { number: 248, text: "Quais regras de frete grátis devem existir no lançamento?" },
      { number: 249, text: "Qual é o fluxo canônico de fulfillment: separação, embalagem, despacho e entrega?" },
      { number: 250, text: "Múltiplos centros de distribuição são suportados no lançamento?" },
      { number: 251, text: "Se houver divergência entre status logístico e status do pedido, quem vence e como reconciliar?" },
      { number: 252, text: "O lojista pode sobrescrever frete, prazo ou rastreamento manualmente? Em quais cenários?" },
    ],
  },
  {
    key: "bloco_ad",
    title: "Bloco AD – Email Marketing",
    questions: [
      { number: 253, text: "Qual é o fluxo canônico de criação, agendamento e envio de campanhas de email marketing?" },
      { number: 254, text: "Quais triggers oficiais devem disparar automações e sequências de email?" },
      { number: 255, text: "A segmentação principal deve ser por listas, tags, filtros de comportamento ou modelo híbrido?" },
      { number: 256, text: "Quais limites de envio por plano devem existir?" },
      { number: 257, text: "Quais métricas são obrigatórias no lançamento: abertura, clique, bounce, unsubscribe, conversão ou outras?" },
      { number: 258, text: "Qual é a fonte de verdade do envio: sistema interno, provedor externo ou modelo híbrido?" },
      { number: 259, text: "Campanhas e automações podem usar o mesmo motor de segmentação ou precisam de regras separadas?" },
      { number: 260, text: "Se houver conflito entre lista, tag, subscriber e customer, qual base prevalece para envio de email marketing?" },
    ],
  },
  {
    key: "bloco_ae",
    title: "Bloco AE – Checkout Abandonado / Recuperação",
    questions: [
      { number: 261, text: "Qual é o fluxo canônico de recuperação de checkout abandonado?" },
      { number: 262, text: "A partir de quanto tempo de inatividade o checkout entra oficialmente no fluxo de recuperação?" },
      { number: 263, text: "Quais canais de recuperação devem ser usados no lançamento: email, WhatsApp, ambos ou outro?" },
      { number: 264, text: "Quantas tentativas de recuperação são permitidas por checkout abandonado?" },
      { number: 265, text: "Em quais momentos as tentativas devem acontecer (ex.: imediata, 1 hora, 24 horas, outros)?" },
      { number: 266, text: "A recuperação pode oferecer desconto automático? Se sim, com quais regras e limites?" },
      { number: 267, text: "Como registrar que uma conversão veio de recuperação de checkout abandonado?" },
      { number: 268, text: "Quando o sistema deve parar automaticamente as tentativas de recuperação?" },
      { number: 269, text: "Como impedir conflito entre recuperação de checkout, pedido já criado, pagamento já aprovado ou nova sessão do cliente?" },
    ],
  },
];

export const totalQuestions = questionnaireBlocks.reduce(
  (sum, block) => sum + block.questions.length,
  0
);
